export const siteConfig = {
  name: "ChinaTripCheck",
  wordmark: "ChinaTripCheck",
  url: "https://chinatripcheck.com",
  description:
    "Run pre-trip China readiness checks for apps, payment and dual-SIM resilience, passport carry needs, train booking, travel dates and hotel arrival.",
  ogImage: "/images/china-trip-check-hero.png",
  lastReviewedAt: "2026-07-15",
  keywords: [
    "China travel preparation",
    "China trip checklist",
    "Alipay setup",
    "WeChat Pay foreigner",
    "China hotel check-in",
    "China travel risk",
    "China holiday calendar",
    "China eSIM",
    "Canton Fair travel",
    "China travel apps",
    "12306 foreign passport",
    "WeChat dual SIM China",
    "carry passport in China",
    "China train tickets",
  ],
} as const;
