export const siteConfig = {
  name: "ChinaTripCheck",
  wordmark: "ChinaTripCheck",
  url: "https://chinatripcheck.com",
  description:
    "Free China travel tools: check visa-free options, calculate train ticket sale and station arrival times, and prepare Alipay, WeChat, apps and hotels.",
  ogImage: "/images/china-trip-check-hero.png",
  lastReviewedAt: "2026-08-03",
  keywords: [
    "China travel preparation",
    "China travel readiness checker",
    "China travel",
    "China payment",
    "China trip checklist",
    "Alipay setup",
    "WeChat Pay foreigner",
    "China hotel check-in",
    "China travel risk",
    "China holiday calendar",
    "China eSIM",
    "Canton Fair travel",
    "China travel apps",
    "12306 foreign passport",
    "WeChat dual SIM China",
    "carry passport in China",
    "China train tickets",
    "China passport travel",
    "China entry preparation",
  ],
} as const;
