import type { GuideSlug } from "./types";

export const guideHowTos: Record<GuideSlug, { name: string; text: string }[]> = {
  "test-mobile-payment-before-china": [
    { name: "Complete identity verification", text: "Open Alipay or WeChat Pay and finish the in-app identity verification before you travel." },
    { name: "Link a foreign card", text: "Link the card you plan to use and enable overseas transactions with the issuer." },
    { name: "Keep approval access ready", text: "Make sure you can reach the number or banking app used for transaction approvals." },
    { name: "Prepare backups", text: "Add a second card from another issuer and carry a small amount of RMB cash." },
    { name: "Make a real purchase", text: "Buy something small through the same app and card combination you plan to use in China." },
    { name: "Repeat after changes", text: "Run the test again if you change cards, phone numbers or app accounts." },
  ],
  "foreign-card-fails-in-china": [
    { name: "Prepare before travel", text: "Tell your issuer how you will approve unusual transactions, carry a second card and keep emergency RMB cash." },
    { name: "Switch to a backup", text: "When a card declines, try your second prepared method instead of repeating the same transaction." },
    { name: "Check issuer alerts", text: "Look for an approval request or fraud alert from your issuer." },
    { name: "Match identity details", text: "Confirm your identity and linked card details match across the payment app and issuer." },
    { name: "Contact issuer if blocked", text: "Reach your issuer through a verified support channel if the card remains declined." },
  ],
  "esim-bank-verification-messages": [
    { name: "Check eSMS support", text: "Confirm whether your travel eSIM includes a phone number and incoming SMS." },
    { name: "Ask about app approvals", text: "Check with your bank whether approvals can happen in its app instead of SMS." },
    { name: "Test while abroad", text: "Try receiving a bank message while the travel data plan is active before you depend on it." },
    { name: "Understand roaming costs", text: "Check charges for keeping your original SIM enabled for verification codes." },
    { name: "Build a fallback", text: "Keep the bank app signed in on a trusted device, carry another card and some RMB cash." },
  ],
  "one-payment-method-is-not-enough": [
    { name: "Test the primary method", text: "Confirm your main Alipay or WeChat Pay path works with a real purchase." },
    { name: "Add a physical card backup", text: "Carry a physical card from another issuer, stored separately from your phone." },
    { name: "Keep cash reserve", text: "Carry a modest amount of RMB cash for cases when digital payment fails." },
    { name: "Confirm issuer settings", text: "Make sure both issuers allow overseas transactions and that you can approve them." },
    { name: "Store backups separately", text: "Keep the backup card and cash in a different place from your phone and main wallet." },
  ],
  "cash-and-atms-in-china": [
    { name: "Exchange emergency cash", text: "Get a modest amount of RMB before you need it, enough for transport, a meal and a buffer." },
    { name: "Split storage", text: "Keep some cash in your wallet and some in your luggage." },
    { name: "Carry a second card", text: "Bring a physical card from a second issuer for ATM withdrawals." },
    { name: "Enable overseas withdrawals", text: "Ask your bank to allow overseas ATM withdrawals before departure." },
    { name: "Test mobile payment", text: "Confirm Alipay or WeChat Pay work so cash stays a backup." },
  ],
  "arrive-with-working-internet": [
    { name: "Choose a primary data plan", text: "Install and activate a travel eSIM or confirm a local SIM purchase plan before departure." },
    { name: "Plan a backup connection", text: "Keep a second eSIM, airport SIM option or a trusted companion hotspot." },
    { name: "Save offline details", text: "Store hotel name and address in Chinese, booking references and emergency contacts offline." },
    { name: "Test on cellular data", text: "Disable Wi-Fi and confirm maps, payment apps and hotel contact pages load." },
    { name: "Document recovery steps", text: "Write down how to buy a local SIM at the arrival airport if the primary plan fails." },
  ],
  "buy-sim-or-esim-for-china": [
    { name: "Install before departure", text: "Install and activate an eSIM that covers mainland China data before you leave." },
    { name: "Confirm data works", text: "Disable Wi-Fi and load a map to confirm the plan is active." },
    { name: "Save hotel details offline", text: "Keep the Chinese hotel address and phone number accessible without data." },
    { name: "Plan an airport SIM fallback", text: "Note where to buy a local SIM at the arrival airport if the eSIM fails." },
    { name: "Restore data first on arrival", text: "If connectivity fails, fix data before relying on payment or ride-hailing apps." },
  ],
  "vpn-in-china-2026": [
    { name: "Install a mainland data plan", text: "Set a primary and backup data plan so local apps work on arrival." },
    { name: "Save key details offline", text: "Keep hotel name, Chinese address, booking codes and emergency contacts offline." },
    { name: "Screenshot reservations", text: "Capture tickets and reservation pages you may need at check-in." },
    { name: "Keep a second contact channel", text: "Save hotel phone, booking platform chat and downloaded emails." },
    { name: "Confirm lawful access method", text: "If you need home services, confirm a lawful method with your employer or provider before travel." },
  ],
  "china-holidays-tickets-hotels": [
    { name: "Compare dates with the holiday calendar", text: "Check official Chinese public holiday dates and the days immediately before and after." },
    { name: "Prioritize critical bookings", text: "Book intercity transport and the first night in each city first." },
    { name: "Use exact passport details", text: "Enter the name and passport number exactly as they appear on the physical passport." },
    { name: "Keep alternatives ready", text: "Identify one acceptable alternative route, time or hotel." },
    { name: "Verify bookings are issued", text: "Confirm each booking is issued, not only requested or waitlisted." },
  ],
  "travel-during-china-national-day": [
    { name: "Decide deliberately", text: "Weigh fixed holiday dates against lower demand and easier last-minute changes." },
    { name: "Book early", text: "Reserve critical transport and accommodation as early as practical." },
    { name: "Limit connections", text: "Reduce same-day connections and optional city changes." },
    { name: "Confirm passport details", text: "Check that issued bookings match your passport exactly." },
    { name: "Reserve attractions", text: "Book timed attractions where required and plan lower-priority alternatives." },
  ],
  "confirm-late-hotel-check-in-china": [
    { name: "Check front desk hours", text: "Ask whether the front desk is open at your expected arrival time in China local time." },
    { name: "Request written confirmation", text: "Get written late-arrival confirmation with the booking name and date." },
    { name: "Save hotel contact offline", text: "Keep the hotel phone number and Chinese address accessible without data." },
    { name: "Identify a backup hotel", text: "Find one nearby 24-hour hotel within a short taxi ride." },
    { name: "Act if confirmation is missing", text: "Treat the stay as incomplete and change to a 24-hour property if confirmation never arrives." },
  ],
  "save-hotel-name-address-in-chinese": [
    { name: "Save the Chinese hotel name", text: "Ask the hotel for the official name in Chinese characters." },
    { name: "Save the full address", text: "Keep the complete Chinese street address, district and city." },
    { name: "Add the phone number", text: "Store the hotel telephone number for driver or support calls." },
    { name: "Keep a map pin and note", text: "Save a map pin and any entrance or exterior note from the property." },
    { name: "Test offline access", text: "Open the saved material with mobile data and Wi-Fi turned off." },
  ],
  "didi-without-chinese-number": [
    { name: "Install and sign up early", text: "Complete DiDi signup while you still have reliable SMS or email verification." },
    { name: "Add a payment method", text: "Link Alipay, WeChat Pay or a card the app accepts and confirm it stays selected." },
    { name: "Save the destination", text: "Store your first hotel's Chinese name and address as a favorite destination." },
    { name: "Test on cellular data", text: "Confirm the app opens on cellular data, not only hotel Wi-Fi." },
    { name: "Keep a taxi desk backup", text: "Have the official taxi queue or hotel pickup plan ready if DiDi fails." },
  ],
  "first-city-shanghai-or-beijing": [
    { name: "Check late-arrival fit", text: "Confirm your flight arrives near a hotel with confirmed late check-in." },
    { name: "Confirm local readiness", text: "Make sure you have Chinese hotel details and a working payment path." },
    { name: "Estimate transfer time", text: "Calculate airport-to-hotel transfer time after midnight." },
    { name: "Add a buffer if needed", text: "Decide whether you need a buffer night before intercity travel." },
  ],
  "china-entry-requirements-checklist": [
    { name: "Check passport validity", text: "Verify your passport is valid for the required period based on your nationality." },
    { name: "Confirm visa or visa-free eligibility", text: "Check whether you need a visa, visa-free entry or another authorization." },
    { name: "Prepare onward or return proof", text: "Keep proof of onward or return travel and the first hotel booking." },
    { name: "Carry offline copies", text: "Pack printed or offline copies in case phones or foreign email apps fail on arrival." },
    { name: "Verify before leaving", text: "Re-read the latest official note for your nationality before departure." },
  ],
};
