import type { ToolConfig } from "../types";
import { choice, yesNo, yesNoUnsure } from "./shared";

export const appsConfig: ToolConfig = {
  slug: "apps",
  name: "China App Readiness Checker",
  shortName: "App readiness",
  description: "Know which apps to install, register and verify before you land.",
  duration: "3 minutes",
  lastReviewedAt: "2026-07-21",
  coveragePoints: [
    "Payment apps and foreign-card verification",
    "Maps and ride-hailing access for arrival day",
    "Train booking channel and passport identity status",
    "Original number access for bank or app recovery",
  ],
  sampleFinding: {
    severity: "critical",
    title: "You may land without a usable payment app.",
    explanation: "A small setup gap can affect transport, food and the first hotel journey.",
  },
  faqs: [
    { question: "Do I need every China travel app?", answer: "No. This check only recommends apps that match your plan. A payment path, maps and a way to book or manage trains are the core decisions." },
    { question: "Does having an app installed mean it is ready?", answer: "No. Registration, identity checks and a real test can still be required. The report separates install, verification and backup risks." },
  ],
  sources: [
    { label: "Alipay: Visiting China", url: "https://www.alipay.com/global/visiting-china/" },
    { label: "12306 English site", url: "https://www.12306.cn/en/index.html" },
  ],
  questions: [
    choice("originalNumber", "Will you keep access to your original mobile number?", yesNoUnsure, "Some issuers and apps may use the registered number for a code or account recovery.", "Your setup"),
    choice("needsPayment", "Will you use mobile payment for everyday spending?", yesNo, undefined, "Payments"),
    { id: "paymentApps", prompt: "Which payment apps have you installed and opened?", type: "multiple", required: true, section: "Payments", options: [
      { label: "Alipay", value: "alipay" },
      { label: "WeChat Pay", value: "wechat" },
      { label: "Neither yet", value: "none", exclusive: true },
    ] },
    choice("identityVerified", "Have you completed the relevant identity verification?", yesNoUnsure, "A downloaded app is not the same as an account that can transact.", "Verification"),
    choice("mapsReady", "Do you have a map app ready for China?", yesNoUnsure, "Save key places offline as a recovery path.", "Getting around"),
    choice("rideReady", "Do you have a ride-hailing plan for airport or station arrival?", yesNoUnsure, undefined, "Getting around"),
    choice("needsTrain", "Will you take a train during this trip?", yesNo, undefined, "Trains"),
    { id: "trainChannel", prompt: "Which train booking channel will you use?", type: "single", required: true, section: "Trains", options: [
      { label: "12306", value: "12306" },
      { label: "Trip.com", value: "trip" },
      { label: "A station counter or agent", value: "station" },
      { label: "I have not chosen one", value: "none" },
    ] },
    choice("trainIdentity", "If you book trains, has your passport identity been accepted?", yesNoUnsure, undefined, "Trains"),
  ],
  rules: [
    {
      code: "APP_NO_PAYMENT_PATH", severity: "critical", priority: 1, group: "app-payment-path",
      all: [{ field: "needsPayment", operator: "eq", value: true }],
      any: [{ field: "paymentApps", operator: "includes", value: "none" }, { field: "identityVerified", operator: "not-yes" }],
      title: "Your planned payment app is not ready yet.",
      explanation: "Installing an app without a verified account can still leave you unable to pay on arrival.",
      actions: ["Open Alipay or WeChat Pay before departure.", "Complete identity verification and link a usable card.", "Keep a physical card or RMB cash as a fallback."],
      relatedCheck: "payment", relatedGuides: ["test-mobile-payment-before-china"],
    },
    {
      code: "APP_NO_MAPS", severity: "high", priority: 2, group: "app-maps",
      all: [{ field: "mapsReady", operator: "not-yes" }],
      title: "Your arrival navigation plan is incomplete.",
      explanation: "A map app and saved hotel details reduce dependence on an unfamiliar airport or station connection.",
      actions: ["Install and open a map app that covers your China destinations.", "Save the hotel name, address and station in Chinese."],
      relatedCheck: "hotel-arrival", relatedGuides: ["save-hotel-name-address-in-chinese"],
    },
    {
      code: "APP_NO_RIDE", severity: "high", priority: 3, group: "app-rides",
      all: [{ field: "rideReady", operator: "not-yes" }],
      title: "You do not have a clear airport or station ride plan.",
      explanation: "The first transfer is when a missing ride option is most disruptive.",
      actions: ["Prepare a ride-hailing or official taxi plan before arrival.", "Save your destination in Chinese."],
      relatedGuides: ["didi-without-chinese-number"],
    },
    {
      code: "APP_TRAIN_CHANNEL", severity: "critical", priority: 4, group: "app-train-channel",
      all: [{ field: "needsTrain", operator: "eq", value: true }, { field: "trainChannel", operator: "eq", value: "none" }],
      title: "Your train booking channel is undecided.",
      explanation: "Without a chosen channel, passport verification and ticket timing cannot be checked.",
      actions: ["Choose 12306, Trip.com or a station counter and complete the passenger setup."],
      relatedCheck: "train-booking",
    },
    {
      code: "APP_TRAIN_IDENTITY", severity: "high", priority: 5, group: "app-train-identity",
      all: [{ field: "needsTrain", operator: "eq", value: true }, { field: "trainIdentity", operator: "not-yes" }],
      title: "Train passport verification still needs attention.",
      explanation: "A ticket channel may accept your booking request while the passenger identity is still pending review.",
      actions: ["Check the passenger status and keep the original passport used for booking."],
      relatedCheck: "train-booking",
    },
    {
      code: "APP_NUMBER", severity: "high", priority: 6, group: "app-number-access",
      all: [{ field: "originalNumber", operator: "not-yes" }],
      title: "Your original number may not be available for recovery.",
      explanation: "A data-only travel SIM does not automatically provide access to bank or account verification messages.",
      actions: ["Keep your original number active or confirm an app-based approval path before departure."],
      relatedGuides: ["esim-bank-verification-messages"],
    },
  ],
};
