import type { ToolConfig } from "../types";
import { choice, yesNo, yesNoUnsure } from "./shared";

export const hotelArrivalConfig: ToolConfig = {
  slug: "hotel-arrival",
  name: "Hotel Arrival Check",
  shortName: "Hotel arrival",
  description: "Check whether your hotel arrival has a reliable primary and backup path.",
  duration: "3 minutes",
  lastReviewedAt: "2026-07-14",
  coveragePoints: [
    "Late arrival and 24-hour front desk confirmation",
    "Hotel name and address saved in Chinese",
    "Passport name match on the booking",
    "Nearby backup hotel and arrival transport plan",
  ],
  sampleFinding: {
    severity: "critical",
    title: "Your late hotel arrival is not confirmed.",
    explanation: "The hotel may release the room or close its front desk before you arrive.",
  },
  questions: [
    { id: "city", prompt: "Which city is the hotel in?", type: "text", required: true, section: "Stay details" },
    { id: "hotelArrivalTime", prompt: "What time do you expect to reach the hotel?", help: "Use China local time in 24-hour format (for example 23:30).", type: "time", required: true, section: "Stay details" },
    choice("frontDesk24Hours", "Does the hotel confirm a 24-hour front desk?", yesNoUnsure, undefined, "Late arrival"),
    choice("lateArrivalConfirmed", "Do you have written late-arrival confirmation?", yesNoUnsure, undefined, "Late arrival"),
    choice("chineseHotelName", "Have you saved the hotel name in Chinese?", yesNoUnsure, undefined, "Local details"),
    choice("chineseAddress", "Have you saved the full address in Chinese?", yesNoUnsure, undefined, "Local details"),
    choice("hotelPhone", "Have you saved the hotel phone number?", yesNoUnsure, undefined, "Local details"),
    choice("bookingNameMatches", "Does the booking name match the passport?", yesNoUnsure, undefined, "Booking"),
    choice("mainstreamPlatform", "Was the stay booked through a recognized platform or directly?", yesNoUnsure, undefined, "Booking"),
    choice("freeCancellation", "Can the booking still be cancelled without charge?", yesNoUnsure, undefined, "Booking"),
    choice("backupHotel", "Have you identified a nearby 24-hour backup hotel?", yesNoUnsure, undefined, "Backup"),
    choice("arrivalTransport", "Do you have a working transport and payment plan for arrival?", yesNoUnsure, undefined, "Backup"),
  ],
  rules: [
    {
      code: "HOTEL_LATE_UNCONFIRMED", severity: "critical", priority: 1, group: "late-arrival-unconfirmed",
      all: [
        { field: "hotelArrivalTime", operator: "time-between", value: { start: "23:00", end: "05:00" } },
        { field: "frontDesk24Hours", operator: "not-yes" },
        { field: "lateArrivalConfirmed", operator: "not-yes" },
      ],
      title: "Your late arrival has no confirmed check-in path.",
      explanation: "The front desk may be closed and the room may not be held.",
      actions: ["Request written late-arrival confirmation.", "Identify a 24-hour backup hotel."],
      backup: "Keep the address and phone number of a nearby 24-hour hotel.",
      relatedGuides: ["confirm-late-hotel-check-in-china"],
    },
    {
      code: "HOTEL_DETAILS", severity: "critical", priority: 2, group: "hotel-details-unusable",
      all: [{ field: "chineseHotelName", operator: "not-yes" }, { field: "chineseAddress", operator: "not-yes" }],
      title: "Your hotel details may not be usable locally.",
      explanation: "Drivers and local maps may not recognize the English name alone.",
      actions: ["Save the hotel name and full address in Chinese."],
      relatedGuides: ["save-hotel-name-address-in-chinese"],
    },
    {
      code: "HOTEL_NAME_MISMATCH", severity: "critical", priority: 3, group: "booking-name-mismatch",
      all: [{ field: "bookingNameMatches", operator: "not-yes" }],
      title: "The booking name does not match the passport.",
      explanation: "A mismatch can delay or prevent identity verification at check-in.",
      actions: ["Ask the booking provider or hotel to correct the guest name before arrival."],
    },
    {
      code: "HOTEL_NO_PHONE", severity: "high", priority: 10, group: "no-hotel-phone",
      all: [{ field: "hotelPhone", operator: "not-yes" }],
      title: "You have no direct hotel phone number.",
      explanation: "A driver or support agent may need to contact the property on arrival.",
      actions: ["Save the hotel's direct phone number offline."],
    },
    {
      code: "HOTEL_NO_TRANSPORT", severity: "critical", priority: 4, group: "no-arrival-transport",
      all: [{ field: "arrivalTransport", operator: "not-yes" }],
      title: "Your arrival transport or payment path is not ready.",
      explanation: "A late arrival can become difficult if you cannot book or pay for transport.",
      actions: ["Prepare a working transport app, payment method and Chinese hotel address."],
    },
    {
      code: "HOTEL_NO_CANCEL", severity: "information", priority: 30, group: "no-cancellation-option",
      all: [{ field: "freeCancellation", operator: "not-yes" }],
      title: "The booking has limited cancellation flexibility.",
      explanation: "A failed arrival plan may make a last-minute change more expensive.",
      actions: ["Confirm the late-arrival terms before the cancellation deadline."],
    },
    {
      code: "HOTEL_NO_BACKUP", severity: "high", priority: 11, group: "no-backup-hotel",
      all: [{ field: "backupHotel", operator: "not-yes" }, { field: "hotelArrivalTime", operator: "time-between", value: { start: "23:00", end: "05:00" } }],
      title: "A late arrival has no backup hotel.",
      explanation: "Finding a suitable property after midnight may be slow and stressful.",
      actions: ["Save one nearby hotel with a confirmed 24-hour front desk."],
      backup: "Keep the backup hotel's Chinese address and phone number offline.",
    },
    {
      code: "HOTEL_NAME_ONLY", severity: "high", priority: 12, group: "missing-chinese-name",
      all: [{ field: "chineseHotelName", operator: "not-yes" }, { field: "chineseAddress", operator: "eq", value: true }],
      title: "The hotel Chinese name is missing.",
      explanation: "Drivers often search by the Chinese property name first.",
      actions: ["Save the hotel name in Chinese as well as the address."],
      relatedGuides: ["save-hotel-name-address-in-chinese"],
    },
    {
      code: "HOTEL_ADDRESS_ONLY", severity: "high", priority: 13, group: "missing-chinese-address",
      all: [{ field: "chineseAddress", operator: "not-yes" }, { field: "chineseHotelName", operator: "eq", value: true }],
      title: "The hotel Chinese address is missing.",
      explanation: "A Chinese name without a full address can still send a driver to the wrong place.",
      actions: ["Save the full Chinese address offline."],
      relatedGuides: ["save-hotel-name-address-in-chinese"],
    },
    {
      code: "HOTEL_NON_MAINSTREAM", severity: "information", priority: 31, group: "non-mainstream-booking",
      all: [{ field: "mainstreamPlatform", operator: "not-yes" }],
      title: "The booking channel may be harder to support.",
      explanation: "Less recognized booking paths can make late changes or confirmation slower.",
      actions: ["Save written hotel confirmation and a direct hotel contact."],
    },
    {
      code: "HOTEL_NO_24H", severity: "high", priority: 14, group: "no-24h-desk",
      all: [
        { field: "hotelArrivalTime", operator: "time-between", value: { start: "23:00", end: "05:00" } },
        { field: "frontDesk24Hours", operator: "not-yes" },
      ],
      title: "Late arrival meets a non-24-hour front desk.",
      explanation: "Without a 24-hour desk, written late-arrival terms become essential.",
      actions: ["Confirm late check-in in writing or choose a 24-hour property."],
      relatedGuides: ["confirm-late-hotel-check-in-china"],
    },
  ],
};
