import type { ToolConfig } from "../types";
import { choice, yesNo } from "./shared";

export const hotelArrivalConfig: ToolConfig = {
  slug: "hotel-arrival",
  name: "Hotel Arrival Check",
  shortName: "Hotel arrival",
  description: "Check whether your hotel arrival has a reliable primary and backup path.",
  duration: "3 minutes",
  lastReviewedAt: "2026-07-14",
  questions: [
    { id: "city", prompt: "Which city is the hotel in?", type: "text", required: true },
    { id: "hotelArrivalTime", prompt: "What time do you expect to reach the hotel?", type: "time", required: true },
    choice("frontDesk24Hours", "Does the hotel confirm a 24-hour front desk?"),
    choice("lateArrivalConfirmed", "Do you have written late-arrival confirmation?"),
    choice("chineseHotelName", "Have you saved the hotel name in Chinese?", yesNo),
    choice("chineseAddress", "Have you saved the full address in Chinese?", yesNo),
    choice("hotelPhone", "Have you saved the hotel phone number?", yesNo),
    choice("bookingNameMatches", "Does the booking name match the passport?"),
    choice("mainstreamPlatform", "Was the stay booked through a recognized platform or directly?"),
    choice("freeCancellation", "Can the booking still be cancelled without charge?", yesNo),
    choice("backupHotel", "Have you identified a nearby 24-hour backup hotel?", yesNo),
    choice("arrivalTransport", "Do you have a working transport and payment plan for arrival?"),
  ],
  rules: [
    {
      code: "HOTEL_LATE_UNCONFIRMED", severity: "critical", priority: 1, group: "late-arrival-unconfirmed",
      all: [
        { field: "hotelArrivalTime", operator: "time-between", value: { start: "23:00", end: "05:00" } },
        { field: "frontDesk24Hours", operator: "eq", value: false },
        { field: "lateArrivalConfirmed", operator: "eq", value: false },
      ],
      title: "Your late arrival has no confirmed check-in path.",
      explanation: "The front desk may be closed and the room may not be held.",
      actions: ["Request written late-arrival confirmation.", "Identify a 24-hour backup hotel."],
      backup: "Keep the address and phone number of a nearby 24-hour hotel.",
      relatedGuides: ["confirm-late-hotel-check-in-china"],
    },
    {
      code: "HOTEL_DETAILS", severity: "critical", priority: 2, group: "hotel-details-unusable",
      all: [{ field: "chineseHotelName", operator: "eq", value: false }, { field: "chineseAddress", operator: "eq", value: false }],
      title: "Your hotel details may not be usable locally.",
      explanation: "Drivers and local maps may not recognize the English name alone.",
      actions: ["Save the hotel name and full address in Chinese."],
      relatedGuides: ["save-hotel-name-address-in-chinese"],
    },
    {
      code: "HOTEL_NAME_MISMATCH", severity: "critical", priority: 3, group: "booking-name-mismatch",
      all: [{ field: "bookingNameMatches", operator: "eq", value: false }],
      title: "The booking name does not match the passport.",
      explanation: "A mismatch can delay or prevent identity verification at check-in.",
      actions: ["Ask the booking provider or hotel to correct the guest name before arrival."],
    },
    {
      code: "HOTEL_NO_PHONE", severity: "high", priority: 10, group: "no-hotel-phone",
      all: [{ field: "hotelPhone", operator: "eq", value: false }],
      title: "You have no direct hotel phone number.",
      explanation: "A driver or support agent may need to contact the property on arrival.",
      actions: ["Save the hotel's direct phone number offline."],
    },
    {
      code: "HOTEL_NO_TRANSPORT", severity: "critical", priority: 4, group: "no-arrival-transport",
      all: [{ field: "arrivalTransport", operator: "eq", value: false }],
      title: "Your arrival transport or payment path is not ready.",
      explanation: "A late arrival can become difficult if you cannot book or pay for transport.",
      actions: ["Prepare a working transport app, payment method and Chinese hotel address."],
    },
    {
      code: "HOTEL_NO_CANCEL", severity: "information", priority: 30, group: "no-cancellation-option",
      all: [{ field: "freeCancellation", operator: "eq", value: false }],
      title: "The booking has limited cancellation flexibility.",
      explanation: "A failed arrival plan may make a last-minute change more expensive.",
      actions: ["Confirm the late-arrival terms before the cancellation deadline."],
    },
    {
      code: "HOTEL_NO_BACKUP", severity: "high", priority: 11, group: "no-backup-hotel",
      all: [{ field: "backupHotel", operator: "eq", value: false }, { field: "hotelArrivalTime", operator: "time-between", value: { start: "23:00", end: "05:00" } }],
      title: "A late arrival has no backup hotel.",
      explanation: "Finding a suitable property after midnight may be slow and stressful.",
      actions: ["Save one nearby hotel with a confirmed 24-hour front desk."],
      backup: "Keep the backup hotel's Chinese address and phone number offline.",
    },
  ],
};
