import type { ToolConfig } from "../types";
import { choice, yesNo, yesNoUnsure } from "./shared";

export const passportConfig: ToolConfig = {
  slug: "passport",
  name: "Passport Carry & Identity Checker",
  shortName: "Passport carry",
  description: "Know when your original passport is essential and where a copy is only a backup.",
  duration: "2 minutes",
  lastReviewedAt: "2026-07-27",
  coveragePoints: [
    "Hotel check-in and accommodation registration",
    "Flights, high-speed rail and passenger identity checks",
    "Ticketed attractions and real-name reservations",
    "Secure storage, offline copies and loss recovery",
  ],
  sampleFinding: {
    severity: "critical",
    title: "Your next activity may require the original passport.",
    explanation: "A photo or photocopy may not satisfy an in-person identity check.",
  },
  faqs: [
    { question: "Is a passport photo always enough in China?", answer: "No. A photo is a useful recovery copy, but hotels, transport operators or real-name services may need the original document used for the booking." },
    { question: "Should I carry my passport every day?", answer: "Carry the original when your day includes a hotel move, flight, train, identity check or a venue that confirms it is required. Otherwise assess the activity and keep the original securely stored." },
    { question: "What should I prepare in case the passport is lost?", answer: "Keep secure offline and cloud copies of the identity and visa or entry pages, plus your insurer and nearest embassy or consulate contact details." },
  ],
  sources: [{ label: "China Railway 12306 English site", url: "https://www.12306.cn/en/index.html" }],
  questions: [
    choice("hotelCheckIn", "Will you check into or change hotels that day?", yesNo, undefined, "Your day"),
    choice("trainTravel", "Will you take a train?", yesNo, undefined, "Your day"),
    choice("flightTravel", "Will you take a domestic or international flight?", yesNo, undefined, "Your day"),
    choice("ticketedAttraction", "Will you visit a ticketed attraction with a real-name booking?", yesNoUnsure, undefined, "Your day"),
    choice("otherIdentityService", "Will you use another service that has asked for passport identification?", yesNoUnsure, undefined, "Your day"),
    choice("originalAvailable", "Will the original passport be available for these activities?", yesNoUnsure, "A photo or photocopy is a backup, not a guaranteed substitute.", "Document"),
    choice("bookingMatches", "Do all passenger and guest names match the passport exactly?", yesNoUnsure, undefined, "Document"),
    choice("secureCopy", "Do you have a secure copy of the identity and entry pages?", yesNoUnsure, undefined, "Recovery"),
    choice("lossContacts", "Have you saved your embassy or consulate and insurer contact details?", yesNoUnsure, undefined, "Recovery"),
  ],
  rules: [
    {
      code: "PASSPORT_HOTEL_ORIGINAL", severity: "critical", priority: 1, group: "original-required",
      all: [{ field: "hotelCheckIn", operator: "eq", value: true }, { field: "originalAvailable", operator: "not-yes" }],
      title: "Hotel check-in may fail without the original passport.",
      explanation: "The property may need the original travel document for guest identity and accommodation registration.",
      actions: ["Carry the original passport used for the booking.", "Confirm the guest name matches it exactly."],
      relatedCheck: "hotel-arrival",
    },
    {
      code: "PASSPORT_TRAIN_ORIGINAL", severity: "critical", priority: 2, group: "original-required",
      all: [{ field: "trainTravel", operator: "eq", value: true }, { field: "originalAvailable", operator: "not-yes" }],
      title: "Train travel may fail without the original passport.",
      explanation: "The travel document connected to the passenger record may be needed for identity checks and station assistance.",
      actions: ["Carry the original passport used to create the passenger and ticket record.", "Allow extra time if manual verification is needed."],
      relatedCheck: "train-booking",
    },
    {
      code: "PASSPORT_FLIGHT_ORIGINAL", severity: "critical", priority: 3, group: "original-required",
      all: [{ field: "flightTravel", operator: "eq", value: true }, { field: "originalAvailable", operator: "not-yes" }],
      title: "Flight check-in requires a reliable original identity document.",
      explanation: "A stored photo should not be treated as a substitute for the travel document on the booking.",
      actions: ["Carry the original passport used for the flight booking.", "Check the airline's document requirements before leaving."],
    },
    {
      code: "PASSPORT_ATTRACTION_CONFIRM", severity: "high", priority: 10, group: "attraction-identity",
      all: [{ field: "ticketedAttraction", operator: "eq", value: true }, { field: "originalAvailable", operator: "not-yes" }],
      title: "Your attraction booking may need an original identity check.",
      explanation: "Real-name ticket rules vary by venue, and the booking document may be checked at entry.",
      actions: ["Check the venue's official entry instructions.", "Carry the original passport if the venue does not explicitly accept a copy."],
    },
    {
      code: "PASSPORT_OTHER_SERVICE", severity: "high", priority: 11, group: "other-identity",
      all: [{ field: "otherIdentityService", operator: "eq", value: true }, { field: "originalAvailable", operator: "not-yes" }],
      title: "A planned real-name service has no reliable identity document.",
      explanation: "The service has already indicated that passport identification may be part of the transaction.",
      actions: ["Ask the provider whether the original is required.", "Carry it unless the provider confirms another accepted document."],
    },
    {
      code: "PASSPORT_NAME_MISMATCH", severity: "critical", priority: 4, group: "identity-match",
      all: [{ field: "bookingMatches", operator: "not-yes" }],
      title: "A booking name may not match the passport.",
      explanation: "Name or document-number differences can delay hotel, train, flight or attraction identity checks.",
      actions: ["Compare every booking with the passport biodata page.", "Ask the provider to correct mismatches before travel."],
    },
    {
      code: "PASSPORT_NO_COPY", severity: "high", priority: 12, group: "loss-recovery",
      all: [{ field: "secureCopy", operator: "not-yes" }],
      title: "Passport loss recovery would be harder without a secure copy.",
      explanation: "Copies of the identity and entry pages can help you report the loss and replace travel documents.",
      actions: ["Store encrypted offline and cloud copies separately from the original."],
    },
    {
      code: "PASSPORT_NO_CONTACTS", severity: "information", priority: 30, group: "loss-contacts",
      all: [{ field: "lossContacts", operator: "not-yes" }],
      title: "Your passport loss contacts are not prepared.",
      explanation: "Finding the right consular and insurance contacts after a loss adds avoidable delay.",
      actions: ["Save the nearest embassy or consulate and travel insurer contact details offline."],
    },
  ],
};
