import type { ToolConfig } from "../types";
import { choice, yesNo, yesNoUnsure } from "./shared";

export const paymentConfig: ToolConfig = {
  slug: "payment",
  name: "Payment Setup Check",
  shortName: "Payment",
  description: "Check whether your payment plan has a single point of failure.",
  duration: "3 minutes",
  lastReviewedAt: "2026-07-14",
  questions: [
    { id: "paymentApps", prompt: "Which mobile payment apps have you set up?", type: "multiple", required: true, options: [
      { label: "Alipay", value: "alipay" },
      { label: "WeChat Pay", value: "wechat" },
      { label: "Neither", value: "none", exclusive: true },
    ] },
    choice("identityVerified", "Is your identity verification complete?"),
    choice("foreignCardLinked", "Have you linked a foreign bank card?"),
    choice("overseasTransactions", "Are overseas transactions enabled on that card?"),
    choice("bankVerificationAccess", "Can you receive bank verification messages or app approvals?"),
    choice("paymentTested", "Have you completed a real payment test?", yesNoUnsure, "Linking a card does not prove a transaction will work."),
    choice("backupCard", "Do you have a second card from another issuer?", yesNo),
    choice("physicalCard", "Will you carry a physical bank card?", yesNo),
    choice("cashBackup", "Will you carry a small amount of RMB cash?", yesNo),
    choice("originalNumberAvailable", "Will your original mobile number remain available?"),
    choice("esimReceivesSms", "Can your travel SIM or eSIM receive verification messages?"),
    choice("reliesOnOneApp", "Would one app failure remove your only mobile payment option?"),
  ],
  rules: [
    {
      code: "PAY_NO_PATH", severity: "critical", priority: 1, group: "no-payment-path",
      all: [
        { field: "physicalCard", operator: "eq", value: false },
        { field: "cashBackup", operator: "eq", value: false },
      ],
      any: [
        { field: "paymentApps", operator: "missing" },
        { field: "paymentApps", operator: "includes", value: "none" },
      ],
      title: "You do not have a practical payment path.",
      explanation: "Without mobile payment, a physical card or cash, routine purchases may become impossible.",
      actions: ["Set up and verify a mobile payment app.", "Carry a physical card.", "Carry emergency RMB cash."],
      backup: "Keep a physical card and cash separate from your phone.",
      relatedGuides: ["foreign-card-fails-in-china"],
    },
    {
      code: "PAY_UNTESTED", severity: "high", priority: 10, group: "payment-untested",
      any: [
        { field: "paymentTested", operator: "eq", value: false },
        { field: "paymentTested", operator: "eq", value: "unsure" },
      ],
      title: "Your mobile payment setup is untested.",
      explanation: "A linked card may still fail during a real transaction.",
      actions: ["Complete a small real payment test before departure."],
      relatedGuides: ["test-mobile-payment-before-china"],
    },
    {
      code: "PAY_SINGLE_POINT", severity: "high", priority: 11, group: "payment-single-point",
      all: [
        { field: "backupCard", operator: "eq", value: false },
        { field: "cashBackup", operator: "eq", value: false },
      ],
      title: "Your payment plan has a single point of failure.",
      explanation: "One card or app problem could leave you without a usable fallback.",
      actions: ["Add a card from another issuer.", "Carry emergency RMB cash."],
      backup: "Keep a second payment method in a separate wallet.",
      relatedGuides: ["one-payment-method-is-not-enough"],
    },
    {
      code: "PAY_NO_VERIFICATION", severity: "high", priority: 12, group: "verification-unavailable",
      all: [{ field: "bankVerificationAccess", operator: "eq", value: false }],
      title: "Bank verification may be unavailable.",
      explanation: "Your issuer may block a transaction that cannot be approved by message or app.",
      actions: ["Confirm how your bank approves overseas transactions.", "Keep your original number available if needed."],
      relatedGuides: ["esim-bank-verification-messages"],
    },
    {
      code: "PAY_OVERSEAS_OFF", severity: "high", priority: 13, group: "overseas-transactions-disabled",
      all: [{ field: "overseasTransactions", operator: "eq", value: false }],
      title: "Overseas transactions are not enabled.",
      explanation: "The issuing bank may reject a China transaction before the payment app can process it.",
      actions: ["Enable overseas transactions or contact your card issuer."],
    },
    {
      code: "PAY_NO_PHYSICAL", severity: "information", priority: 30, group: "no-physical-card",
      all: [{ field: "physicalCard", operator: "eq", value: false }],
      title: "You are not carrying a physical card.",
      explanation: "A physical card provides another recovery path when a phone or app is unavailable.",
      actions: ["Pack a physical card and store it separately from your phone."],
    },
    {
      code: "PAY_NO_CASH", severity: "information", priority: 31, group: "no-cash",
      all: [{ field: "cashBackup", operator: "eq", value: false }],
      title: "You have no emergency cash backup.",
      explanation: "Small amounts of RMB can help when a digital payment path is interrupted.",
      actions: ["Carry a modest amount of RMB cash for emergencies."],
    },
    {
      code: "PAY_DATA_ONLY_ESIM", severity: "high", priority: 14, group: "data-only-esim",
      all: [
        { field: "esimReceivesSms", operator: "eq", value: false },
        { field: "originalNumberAvailable", operator: "eq", value: false },
      ],
      title: "Your travel connectivity may not receive bank messages.",
      explanation: "Data access alone may not be enough to approve a transaction.",
      actions: ["Keep access to bank app approvals or your original mobile number."],
      relatedGuides: ["esim-bank-verification-messages"],
    },
    {
      code: "PAY_ONE_APP", severity: "high", priority: 15, group: "one-app-only",
      all: [{ field: "reliesOnOneApp", operator: "eq", value: true }],
      title: "One app failure could stop mobile payments.",
      explanation: "A second app or non-phone fallback reduces dependence on one account.",
      actions: ["Prepare a second payment app or a physical fallback."],
      relatedGuides: ["one-payment-method-is-not-enough"],
    },
  ],
};
