import type { ToolConfig } from "../types";
import { choice, yesNoUnsure } from "./shared";

export const paymentFaqs = [
  { question: "Is linking a foreign card enough?", answer: "No. Linking only proves setup. A small real transaction is the clearest way to confirm the full approval path works abroad." },
  { question: "Will my travel eSIM receive bank verification messages?", answer: "Often no. Many travel eSIMs are data-only. Keep your original number or bank app approvals available." },
  { question: "Why carry RMB cash if I have Alipay?", answer: "Cash is a recovery path when a phone, app, card or network problem blocks digital payment." },
];

export const paymentConfig: ToolConfig = {
  slug: "payment",
  name: "Payment Setup Check",
  shortName: "Payment",
  description: "Check whether your payment plan has a single point of failure.",
  duration: "3 minutes",
  lastReviewedAt: "2026-07-14",
  coveragePoints: [
    "Alipay and WeChat Pay setup and identity verification",
    "Foreign card linking and overseas transaction settings",
    "Bank verification access through SMS or banking app",
    "Second card, physical card and RMB cash backups",
  ],
  sampleFinding: {
    severity: "critical",
    title: "Your payment setup has a single point of failure.",
    explanation: "There is no tested payment path or practical backup if one app or card fails.",
  },
  faqs: paymentFaqs,
  questions: [
    { id: "paymentApps", prompt: "Which mobile payment apps have you set up?", type: "multiple", required: true, section: "Setup", options: [
      { label: "Alipay", value: "alipay" },
      { label: "WeChat Pay", value: "wechat" },
      { label: "Neither", value: "none", exclusive: true },
    ] },
    choice("identityVerified", "Is your identity verification complete?", yesNoUnsure, undefined, "Setup"),
    choice("foreignCardLinked", "Have you linked a foreign bank card?", yesNoUnsure, undefined, "Card"),
    choice("overseasTransactions", "Are overseas transactions enabled on that card?", yesNoUnsure, undefined, "Card"),
    choice("bankVerificationAccess", "Can you receive bank verification messages or app approvals?", yesNoUnsure, undefined, "Verification"),
    choice("paymentTested", "Have you completed a real payment test?", yesNoUnsure, "Linking a card does not prove a transaction will work.", "Verification"),
    choice("backupCard", "Do you have a second card from another issuer?", yesNoUnsure, undefined, "Backup"),
    choice("physicalCard", "Will you carry a physical bank card?", yesNoUnsure, undefined, "Backup"),
    choice("cashBackup", "Will you carry a small amount of RMB cash?", yesNoUnsure, undefined, "Backup"),
    choice("originalNumberAvailable", "Will your original mobile number remain available?", yesNoUnsure, undefined, "Verification"),
    choice("esimReceivesSms", "Can your travel SIM or eSIM receive verification messages?", yesNoUnsure, undefined, "Verification"),
    choice("reliesOnOneApp", "Is Alipay or WeChat Pay your only mobile payment option?", yesNoUnsure, "Answer yes if losing one app would leave you with no other mobile payment path.", "Backup"),
  ],
  rules: [
    {
      code: "PAY_NO_PATH", severity: "critical", priority: 1, group: "no-payment-path",
      all: [
        { field: "physicalCard", operator: "not-yes" },
        { field: "cashBackup", operator: "not-yes" },
      ],
      any: [
        { field: "paymentApps", operator: "missing" },
        { field: "paymentApps", operator: "includes", value: "none" },
      ],
      title: "You do not have a practical payment path.",
      explanation: "Without mobile payment, a physical card or cash, routine purchases may become impossible.",
      actions: ["Set up and verify a mobile payment app.", "Carry a physical card.", "Carry emergency RMB cash."],
      backup: "Keep a physical card and cash separate from your phone.",
      relatedGuides: ["foreign-card-fails-in-china"],
    },
    {
      code: "PAY_NO_APP", severity: "critical", priority: 2, group: "no-payment-app",
      any: [
        { field: "paymentApps", operator: "missing" },
        { field: "paymentApps", operator: "includes", value: "none" },
      ],
      title: "No Alipay or WeChat Pay app is set up.",
      explanation: "Many merchants and transport options expect one of these apps.",
      actions: ["Set up Alipay or WeChat Pay before departure."],
      relatedGuides: ["test-mobile-payment-before-china"],
    },
    {
      code: "PAY_NO_IDENTITY", severity: "high", priority: 3, group: "identity-incomplete",
      all: [{ field: "identityVerified", operator: "not-yes" }],
      any: [
        { field: "paymentApps", operator: "includes", value: "alipay" },
        { field: "paymentApps", operator: "includes", value: "wechat" },
      ],
      title: "Payment app identity verification is incomplete.",
      explanation: "An unfinished identity check can block card linking or purchases.",
      actions: ["Complete identity verification in Alipay or WeChat Pay."],
    },
    {
      code: "PAY_NO_CARD_LINKED", severity: "high", priority: 4, group: "no-card-linked",
      all: [{ field: "foreignCardLinked", operator: "not-yes" }],
      any: [
        { field: "paymentApps", operator: "includes", value: "alipay" },
        { field: "paymentApps", operator: "includes", value: "wechat" },
      ],
      title: "No foreign card is linked to the payment app.",
      explanation: "Without a linked card, the app may not fund purchases.",
      actions: ["Link a usable foreign card and confirm the issuer allows China transactions."],
    },
    {
      code: "PAY_UNTESTED", severity: "high", priority: 10, group: "payment-untested",
      any: [
        { field: "paymentTested", operator: "eq", value: false },
        { field: "paymentTested", operator: "eq", value: "unsure" },
      ],
      title: "Your mobile payment setup is untested.",
      explanation: "A linked card may still fail during a real transaction.",
      actions: ["Complete a small real payment test before departure."],
      relatedGuides: ["test-mobile-payment-before-china"],
    },
    {
      code: "PAY_SINGLE_POINT", severity: "high", priority: 11, group: "payment-single-point",
      all: [
        { field: "backupCard", operator: "not-yes" },
        { field: "cashBackup", operator: "not-yes" },
      ],
      title: "Your payment plan has a single point of failure.",
      explanation: "One card or app problem could leave you without a usable fallback.",
      actions: ["Add a card from another issuer.", "Carry emergency RMB cash."],
      backup: "Keep a second payment method in a separate wallet.",
      relatedGuides: ["one-payment-method-is-not-enough"],
    },
    {
      code: "PAY_NO_VERIFICATION", severity: "high", priority: 12, group: "verification-unavailable",
      all: [{ field: "bankVerificationAccess", operator: "not-yes" }],
      title: "Bank verification may be unavailable.",
      explanation: "Your issuer may block a transaction that cannot be approved by message or app.",
      actions: ["Confirm how your bank approves overseas transactions.", "Keep your original number available if needed."],
      relatedGuides: ["esim-bank-verification-messages"],
    },
    {
      code: "PAY_OVERSEAS_OFF", severity: "high", priority: 13, group: "overseas-transactions-disabled",
      all: [{ field: "overseasTransactions", operator: "not-yes" }],
      title: "Overseas transactions are not enabled.",
      explanation: "The issuing bank may reject a China transaction before the payment app can process it.",
      actions: ["Enable overseas transactions or contact your card issuer."],
    },
    {
      code: "PAY_OVERSEAS_UNSURE", severity: "information", priority: 32, group: "overseas-unsure",
      all: [{ field: "overseasTransactions", operator: "eq", value: "unsure" }],
      title: "Overseas transaction settings still need confirmation.",
      explanation: "An unconfirmed issuer setting can cause a surprise decline abroad.",
      actions: ["Check with your card issuer before departure."],
    },
    {
      code: "PAY_NO_PHYSICAL", severity: "information", priority: 30, group: "no-physical-card",
      all: [{ field: "physicalCard", operator: "not-yes" }],
      title: "You are not carrying a physical card.",
      explanation: "A physical card provides another recovery path when a phone or app is unavailable.",
      actions: ["Pack a physical card and store it separately from your phone."],
    },
    {
      code: "PAY_NO_CASH", severity: "information", priority: 31, group: "no-cash",
      all: [{ field: "cashBackup", operator: "not-yes" }],
      title: "You have no emergency cash backup.",
      explanation: "Small amounts of RMB can help when a digital payment path is interrupted.",
      actions: ["Carry a modest amount of RMB cash for emergencies."],
    },
    {
      code: "PAY_DATA_ONLY_ESIM", severity: "high", priority: 14, group: "data-only-esim",
      all: [
        { field: "esimReceivesSms", operator: "not-yes" },
        { field: "originalNumberAvailable", operator: "not-yes" },
      ],
      title: "Your travel connectivity may not receive bank messages.",
      explanation: "Data access alone may not be enough to approve a transaction.",
      actions: ["Keep access to bank app approvals or your original mobile number."],
      relatedGuides: ["esim-bank-verification-messages"],
    },
    {
      code: "PAY_NUMBER_UNSURE", severity: "information", priority: 33, group: "number-unsure",
      all: [{ field: "originalNumberAvailable", operator: "eq", value: "unsure" }],
      title: "Access to your original number is uncertain.",
      explanation: "Some issuers still send one-time codes to the registered number.",
      actions: ["Confirm how you will approve bank messages while abroad."],
      relatedGuides: ["esim-bank-verification-messages"],
    },
    {
      code: "PAY_ONE_APP", severity: "high", priority: 15, group: "one-app-only",
      all: [{ field: "reliesOnOneApp", operator: "eq", value: true }],
      title: "One app failure could stop mobile payments.",
      explanation: "A second app or non-phone fallback reduces dependence on one account.",
      actions: ["Prepare a second payment app or a physical fallback."],
      relatedGuides: ["one-payment-method-is-not-enough"],
    },
    {
      code: "PAY_CARD_UNSURE", severity: "information", priority: 34, group: "card-link-unsure",
      all: [{ field: "foreignCardLinked", operator: "eq", value: "unsure" }],
      title: "Foreign card linking still needs confirmation.",
      explanation: "An unclear link status can leave the app unfunded on arrival.",
      actions: ["Open the payment app and confirm the linked card status."],
    },
  ],
};
