import type { ToolConfig } from "../types";
import { choice, yesNoUnsure } from "./shared";

export const paymentFaqs = [
  { question: "Is linking a foreign card enough?", answer: "No. Linking only proves setup. A small real transaction is the clearest way to confirm the full approval path works abroad." },
  { question: "Why is my linked Alipay card not working?", answer: "The failure can occur at bank authorization, app risk control, merchant acceptance or the verification channel. The diagnostic separates those stages before recommending a retry." },
  { question: "Will my travel eSIM receive bank verification messages?", answer: "Often no. Many travel eSIMs are data-only. Keep your original number or bank app approvals available." },
  { question: "Why carry RMB cash if I have Alipay?", answer: "Cash is a recovery path when a phone, app, card or network problem blocks digital payment." },
];

export const paymentConfig: ToolConfig = {
  slug: "payment",
  name: "China Payment Preflight & Failure Diagnostic",
  shortName: "Payment diagnostic",
  description: "Find where Alipay, WeChat Pay, card authorization or verification is failing and prepare a usable backup.",
  duration: "5 minutes",
  lastReviewedAt: "2026-08-17",
  coveragePoints: [
    "Account, identity and foreign-card linking failures",
    "Bank authorization, merchant payment and risk-control diagnosis",
    "SMS, banking-app and original-number recovery",
    "Second wallet, independent card, physical card and RMB cash fallbacks",
    "VPN, original-number and account-recovery resilience",
  ],
  sampleFinding: {
    severity: "critical",
    title: "Your payment setup has a single point of failure.",
    explanation: "There is no tested payment path or practical backup if one app or card fails.",
  },
  faqs: paymentFaqs,
  sources: [
    { label: "Alipay: Visiting China", url: "https://www.alipay.com/global/visiting-china/" },
  ],
  questions: [
    { id: "failureStage", prompt: "Where are you in the payment setup or failure path?", type: "single", required: true, section: "Start diagnosis", options: [
      { label: "I have not finished setup", value: "setup" },
      { label: "I cannot add a foreign card", value: "cant-add-card" },
      { label: "I cannot complete identity verification", value: "cant-verify-id" },
      { label: "I cannot receive SMS or bank approval", value: "cant-verify-bank" },
      { label: "The card is linked but payment fails", value: "linked-payment-fails" },
      { label: "The account is frozen or under risk control", value: "risk-control" },
      { label: "I am trying to top up a balance", value: "top-up" },
      { label: "Payment works; I want a preflight check", value: "preflight" },
    ] },
    { id: "paymentApps", prompt: "Which mobile payment apps have you set up?", type: "multiple", required: true, section: "Setup", options: [
      { label: "Alipay", value: "alipay" },
      { label: "WeChat Pay", value: "wechat" },
      { label: "Neither", value: "none", exclusive: true },
    ] },
    choice("identityVerified", "Is your identity verification complete?", yesNoUnsure, undefined, "Setup"),
    choice("foreignCardLinked", "Have you linked a foreign bank card?", yesNoUnsure, undefined, "Card"),
    choice("overseasTransactions", "Are overseas transactions enabled on that card?", yesNoUnsure, undefined, "Card"),
    choice("bankVerificationAccess", "Can you receive bank verification messages or app approvals?", yesNoUnsure, undefined, "Verification"),
    choice("paymentTested", "Have you completed a real payment test?", yesNoUnsure, "Linking a card does not prove a transaction will work.", "Verification"),
    { id: "issuerSignal", prompt: "What does your card issuer show for the failed payment?", type: "single", required: true, section: "Transaction diagnosis", visibleWhen: { field: "failureStage", equals: "linked-payment-fails" }, options: [
      { label: "The issuer declined or blocked it", value: "issuer-declined" },
      { label: "The issuer shows no attempted charge", value: "no-attempt" },
      { label: "The issuer approved it but the app failed", value: "issuer-approved" },
      { label: "I cannot tell", value: "unsure" },
    ] },
    { id: "otherCardResult", prompt: "What happens with a card from another issuer?", type: "single", required: true, section: "Transaction diagnosis", visibleWhen: { field: "failureStage", equals: "linked-payment-fails" }, options: [
      { label: "Another card works", value: "works" },
      { label: "Another card also fails", value: "fails" },
      { label: "I have not tried another issuer", value: "not-tried" },
    ] },
    { id: "merchantScope", prompt: "Where does the payment fail?", type: "single", required: true, section: "Transaction diagnosis", visibleWhen: { field: "failureStage", equals: "linked-payment-fails" }, options: [
      { label: "Only one merchant or payment type", value: "one-merchant" },
      { label: "At several unrelated merchants", value: "several" },
      { label: "I have only tried once", value: "one-test" },
    ] },
    { id: "riskRecovery", prompt: "Does the app offer an appeal or identity recovery step?", type: "single", required: true, section: "Risk control", visibleWhen: { field: "failureStage", equals: "risk-control" }, options: yesNoUnsure },
    { id: "topUpReason", prompt: "Why are you trying to top up the app balance?", type: "single", required: true, section: "Funding method", visibleWhen: { field: "failureStage", equals: "top-up" }, options: [
      { label: "I thought a linked card must first fund the balance", value: "thought-required" },
      { label: "A merchant payment failed", value: "payment-failed" },
      { label: "Someone told me to add balance", value: "advice" },
      { label: "Another reason", value: "other" },
    ] },
    choice("backupCard", "Do you have a second card from another bank or card network?", yesNoUnsure, "The backup should not depend on the same issuer decision as your primary card.", "Backup"),
    choice("physicalCard", "Will you carry a physical bank card?", yesNoUnsure, undefined, "Backup"),
    choice("cashBackup", "Will you carry a small amount of RMB cash?", yesNoUnsure, undefined, "Backup"),
    choice("originalNumberAvailable", "Will your original mobile number remain available?", yesNoUnsure, undefined, "Verification"),
    choice("dualSimReady", "If you will use dual SIM, have you tested which line receives verification messages?", yesNoUnsure, "Choose yes if you are not using dual SIM or have already tested the setup.", "Verification"),
    choice("esimReceivesSms", "Can your travel SIM or eSIM receive verification messages?", yesNoUnsure, undefined, "Verification"),
    choice("reliesOnOneApp", "Is Alipay or WeChat Pay your only mobile payment option?", yesNoUnsure, "Answer yes if losing one app would leave you with no other mobile payment path.", "Backup"),
    choice("vpnPaymentAware", "Will you retry payment or verification with the VPN switched off if the app fails?", yesNoUnsure, "Some payment or verification paths may treat a VPN or unusual IP as a risk signal.", "Recovery"),
  ],
  rules: [
    {
      code: "PAY_CARD_LINK_FAILURE", severity: "high", priority: 2, group: "card-link-failure",
      all: [{ field: "failureStage", operator: "eq", value: "cant-add-card" }],
      title: "CARD LINKING BLOCKER — the payment path is not funded yet.",
      explanation: "The failure occurs before a merchant transaction, so retrying payments will not solve it.",
      actions: ["Confirm the card details and supported card type in the payment app.", "Ask the issuer whether the card can be tokenized and used for overseas digital-wallet transactions."],
      backup: "Prepare a card from another issuer, a physical card and RMB cash.", relatedGuides: ["test-mobile-payment-before-china", "foreign-card-fails-in-china"],
    },
    {
      code: "PAY_ID_FAILURE", severity: "high", priority: 2, group: "identity-verification-failure",
      all: [{ field: "failureStage", operator: "eq", value: "cant-verify-id" }],
      title: "IDENTITY BLOCKER — the account cannot reach transaction readiness.",
      explanation: "Card linking or payment may remain unavailable until the identity record is accepted.",
      actions: ["Compare the name and document details with the original passport.", "Use the in-app identity recovery route before creating duplicate accounts."],
      backup: "Keep another payment app and a non-phone payment method available.", relatedGuides: ["test-mobile-payment-before-china"],
    },
    {
      code: "PAY_BANK_APPROVAL_FAILURE", severity: "critical", priority: 2, group: "bank-approval-failure",
      all: [{ field: "failureStage", operator: "eq", value: "cant-verify-bank" }],
      title: "BANK APPROVAL BLOCKER — the transaction cannot be authenticated.",
      explanation: "A working app and linked card still fail when the issuer challenge cannot reach you.",
      actions: ["Restore access to the registered number or banking-app approval.", "Confirm the issuer's overseas authentication method before another test."],
      backup: "Use a second issuer and keep the original number active for recovery.", relatedGuides: ["esim-bank-verification-messages", "foreign-card-fails-in-china"],
    },
    {
      code: "PAY_ISSUER_DECLINE", severity: "critical", priority: 2, group: "issuer-decline",
      all: [{ field: "failureStage", operator: "eq", value: "linked-payment-fails" }, { field: "issuerSignal", operator: "eq", value: "issuer-declined" }],
      title: "ISSUER DECLINE — the bank is stopping the payment.",
      explanation: "The card reached the issuer, but authorization was refused or blocked.",
      actions: ["Check overseas and online transaction controls with the issuer.", "Try a small payment with a card from another issuer."],
      backup: "Do not keep retrying the same declined card; switch to an independent payment path.", relatedGuides: ["foreign-card-fails-in-china"],
    },
    {
      code: "PAY_APP_OR_RISK_FAILURE", severity: "high", priority: 3, group: "app-or-risk-failure",
      all: [{ field: "failureStage", operator: "eq", value: "linked-payment-fails" }],
      any: [{ field: "issuerSignal", operator: "eq", value: "no-attempt" }, { field: "issuerSignal", operator: "eq", value: "issuer-approved" }],
      title: "APP OR RISK-CONTROL BLOCKER — the issuer is not the clear failure point.",
      explanation: "No issuer attempt or an issuer approval followed by app failure points back to the wallet, account or merchant path.",
      actions: ["Review the payment app error and identity status.", "Avoid repeated rapid attempts and use the app's support or recovery flow."],
      backup: "Switch to another app, merchant payment method or physical fallback.", relatedGuides: ["foreign-card-fails-in-china"],
    },
    {
      code: "PAY_ONE_MERCHANT", severity: "information", priority: 20, group: "merchant-specific-failure",
      all: [{ field: "failureStage", operator: "eq", value: "linked-payment-fails" }, { field: "merchantScope", operator: "eq", value: "one-merchant" }],
      title: "MERCHANT-SPECIFIC FAILURE — the full payment setup may still work.",
      explanation: "A failure limited to one merchant or payment type is weaker evidence of an account-wide problem.",
      actions: ["Test a small purchase at an unrelated merchant.", "Use another accepted payment method for the original merchant."],
      relatedGuides: ["test-mobile-payment-before-china"],
    },
    {
      code: "PAY_SECOND_ISSUER_WORKS", severity: "information", priority: 21, group: "issuer-isolated-failure",
      all: [{ field: "failureStage", operator: "eq", value: "linked-payment-fails" }, { field: "otherCardResult", operator: "eq", value: "works" }],
      title: "The failure is isolated to the first card or issuer.",
      explanation: "A successful second card proves that the app and merchant path can complete a transaction.",
      actions: ["Use the working issuer as the primary card and keep the failed card only as a secondary option."],
      relatedGuides: ["one-payment-method-is-not-enough"],
    },
    {
      code: "PAY_RISK_CONTROL", severity: "critical", priority: 2, group: "payment-risk-control",
      all: [{ field: "failureStage", operator: "eq", value: "risk-control" }],
      title: "RISK-CONTROL FREEZE — stop repeated payment attempts.",
      explanation: "Repeated retries can extend or complicate an account review.",
      actions: ["Use the app's appeal or identity recovery process.", "Preserve screenshots and wait for the stated review outcome before retrying."],
      backup: "Use an independent app, physical card or RMB cash while the account is restricted.", relatedGuides: ["foreign-card-fails-in-china"],
    },
    {
      code: "PAY_TOPUP_CONFUSION", severity: "information", priority: 19, group: "topup-vs-linked-card",
      all: [{ field: "failureStage", operator: "eq", value: "top-up" }],
      title: "TOP-UP IS NOT THE SAME AS LINKING A CARD.",
      explanation: "Foreign visitors should not assume that a linked international card must first fund an app balance before merchant payment.",
      actions: ["Check whether the app supports direct merchant payment from the linked card.", "Do not rely on balance top-up as a workaround without official confirmation."],
      backup: "Test a small direct card-funded merchant payment and retain physical alternatives.", relatedGuides: ["test-mobile-payment-before-china"],
    },
    {
      code: "PAY_NO_PATH", severity: "critical", priority: 1, group: "no-payment-path",
      all: [
        { field: "physicalCard", operator: "not-yes" },
        { field: "cashBackup", operator: "not-yes" },
      ],
      any: [
        { field: "paymentApps", operator: "missing" },
        { field: "paymentApps", operator: "includes", value: "none" },
      ],
      title: "You do not have a practical payment path.",
      explanation: "Without mobile payment, a physical card or cash, routine purchases may become impossible.",
      actions: ["Set up and verify a mobile payment app.", "Carry a physical card.", "Carry emergency RMB cash."],
      backup: "Keep a physical card and cash separate from your phone.",
      relatedGuides: ["foreign-card-fails-in-china"],
    },
    {
      code: "PAY_NO_APP", severity: "critical", priority: 2, group: "no-payment-app",
      any: [
        { field: "paymentApps", operator: "missing" },
        { field: "paymentApps", operator: "includes", value: "none" },
      ],
      title: "No Alipay or WeChat Pay app is set up.",
      explanation: "Many merchants and transport options expect one of these apps.",
      actions: ["Set up Alipay or WeChat Pay before departure."],
      relatedGuides: ["test-mobile-payment-before-china"],
    },
    {
      code: "PAY_NO_IDENTITY", severity: "high", priority: 3, group: "identity-incomplete",
      all: [{ field: "identityVerified", operator: "not-yes" }],
      any: [
        { field: "paymentApps", operator: "includes", value: "alipay" },
        { field: "paymentApps", operator: "includes", value: "wechat" },
      ],
      title: "Payment app identity verification is incomplete.",
      explanation: "An unfinished identity check can block card linking or purchases.",
      actions: ["Complete identity verification in Alipay or WeChat Pay."],
    },
    {
      code: "PAY_NO_CARD_LINKED", severity: "high", priority: 4, group: "no-card-linked",
      all: [{ field: "foreignCardLinked", operator: "not-yes" }],
      any: [
        { field: "paymentApps", operator: "includes", value: "alipay" },
        { field: "paymentApps", operator: "includes", value: "wechat" },
      ],
      title: "No foreign card is linked to the payment app.",
      explanation: "Without a linked card, the app may not fund purchases.",
      actions: ["Link a usable foreign card and confirm the issuer allows China transactions."],
    },
    {
      code: "PAY_UNTESTED", severity: "high", priority: 10, group: "payment-untested",
      any: [
        { field: "paymentTested", operator: "eq", value: false },
        { field: "paymentTested", operator: "eq", value: "unsure" },
      ],
      title: "Your mobile payment setup is untested.",
      explanation: "A linked card may still fail during a real transaction.",
      actions: ["Complete a small real payment test before departure."],
      relatedGuides: ["test-mobile-payment-before-china"],
    },
    {
      code: "PAY_SINGLE_POINT", severity: "high", priority: 11, group: "payment-single-point",
      all: [
        { field: "backupCard", operator: "not-yes" },
        { field: "cashBackup", operator: "not-yes" },
      ],
      title: "Your payment plan has a single point of failure.",
      explanation: "One card or app problem could leave you without a usable fallback.",
      actions: ["Add a card from another issuer.", "Carry emergency RMB cash."],
      backup: "Keep a second payment method in a separate wallet.",
      relatedGuides: ["one-payment-method-is-not-enough"],
    },
    {
      code: "PAY_NO_VERIFICATION", severity: "high", priority: 12, group: "verification-unavailable",
      all: [{ field: "bankVerificationAccess", operator: "not-yes" }],
      title: "Bank verification may be unavailable.",
      explanation: "Your issuer may block a transaction that cannot be approved by message or app.",
      actions: ["Confirm how your bank approves overseas transactions.", "Keep your original number available if needed."],
      relatedGuides: ["esim-bank-verification-messages"],
    },
    {
      code: "PAY_DUAL_SIM_UNTESTED", severity: "high", priority: 13, group: "dual-sim-verification",
      all: [
        { field: "dualSimReady", operator: "not-yes" },
        { field: "originalNumberAvailable", operator: "not-yes" },
      ],
      title: "Your SIM setup may block payment verification.",
      explanation: "Switching data lines does not guarantee that the registered number can receive a bank or account code.",
      actions: ["Keep the original line enabled for messages.", "Test the dual-SIM setup before departure.", "Save a bank-app approval path as backup."],
      relatedGuides: ["esim-bank-verification-messages"],
    },
    {
      code: "PAY_OVERSEAS_OFF", severity: "high", priority: 13, group: "overseas-transactions-disabled",
      all: [{ field: "overseasTransactions", operator: "not-yes" }],
      title: "Overseas transactions are not enabled.",
      explanation: "The issuing bank may reject a China transaction before the payment app can process it.",
      actions: ["Enable overseas transactions or contact your card issuer."],
    },
    {
      code: "PAY_OVERSEAS_UNSURE", severity: "information", priority: 32, group: "overseas-unsure",
      all: [{ field: "overseasTransactions", operator: "eq", value: "unsure" }],
      title: "Overseas transaction settings still need confirmation.",
      explanation: "An unconfirmed issuer setting can cause a surprise decline abroad.",
      actions: ["Check with your card issuer before departure."],
    },
    {
      code: "PAY_NO_PHYSICAL", severity: "information", priority: 30, group: "no-physical-card",
      all: [{ field: "physicalCard", operator: "not-yes" }],
      title: "You are not carrying a physical card.",
      explanation: "A physical card provides another recovery path when a phone or app is unavailable.",
      actions: ["Pack a physical card and store it separately from your phone."],
    },
    {
      code: "PAY_NO_CASH", severity: "information", priority: 31, group: "no-cash",
      all: [{ field: "cashBackup", operator: "not-yes" }],
      title: "You have no emergency cash backup.",
      explanation: "Small amounts of RMB can help when a digital payment path is interrupted.",
      actions: ["Carry a modest amount of RMB cash for emergencies."],
    },
    {
      code: "PAY_DATA_ONLY_ESIM", severity: "high", priority: 14, group: "data-only-esim",
      all: [
        { field: "esimReceivesSms", operator: "not-yes" },
        { field: "originalNumberAvailable", operator: "not-yes" },
      ],
      title: "Your travel connectivity may not receive bank messages.",
      explanation: "Data access alone may not be enough to approve a transaction.",
      actions: ["Keep access to bank app approvals or your original mobile number."],
      relatedGuides: ["esim-bank-verification-messages"],
    },
    {
      code: "PAY_NUMBER_UNSURE", severity: "information", priority: 33, group: "number-unsure",
      all: [{ field: "originalNumberAvailable", operator: "eq", value: "unsure" }],
      title: "Access to your original number is uncertain.",
      explanation: "Some issuers still send one-time codes to the registered number.",
      actions: ["Confirm how you will approve bank messages while abroad."],
      relatedGuides: ["esim-bank-verification-messages"],
    },
    {
      code: "PAY_ONE_APP", severity: "high", priority: 15, group: "one-app-only",
      all: [{ field: "reliesOnOneApp", operator: "eq", value: true }],
      title: "One app failure could stop mobile payments.",
      explanation: "A second app or non-phone fallback reduces dependence on one account.",
      actions: ["Prepare a second payment app or a physical fallback."],
      relatedGuides: ["one-payment-method-is-not-enough"],
    },
    {
      code: "PAY_VPN_UNAWARE", severity: "information", priority: 35, group: "vpn-payment-recovery",
      all: [{ field: "vpnPaymentAware", operator: "not-yes" }],
      title: "Your payment recovery plan does not account for VPN risk.",
      explanation: "A VPN or unusual network path can complicate some app verification or payment attempts.",
      actions: ["If payment or verification fails, stop repeated attempts and retry once on a trusted connection with the VPN switched off."],
      relatedGuides: ["foreign-card-fails-in-china", "vpn-in-china-2026"],
    },
    {
      code: "PAY_HIGH_RESILIENCE", severity: "ready", priority: 50, group: "payment-resilience-ready",
      all: [
        { field: "paymentApps", operator: "includes", value: "alipay" },
        { field: "paymentApps", operator: "includes", value: "wechat" },
        { field: "paymentTested", operator: "eq", value: true },
        { field: "backupCard", operator: "eq", value: true },
        { field: "cashBackup", operator: "eq", value: true },
        { field: "originalNumberAvailable", operator: "eq", value: true },
        { field: "vpnPaymentAware", operator: "eq", value: true },
      ],
      title: "HIGH PAYMENT RESILIENCE — independent recovery paths are ready.",
      explanation: "Two wallets, a tested primary path, an independent card, verification access and emergency cash reduce single-point failure risk.",
      actions: ["Keep the backup card and cash separate from the phone used for mobile payment."],
    },
    {
      code: "PAY_CARD_UNSURE", severity: "information", priority: 34, group: "card-link-unsure",
      all: [{ field: "foreignCardLinked", operator: "eq", value: "unsure" }],
      title: "Foreign card linking still needs confirmation.",
      explanation: "An unclear link status can leave the app unfunded on arrival.",
      actions: ["Open the payment app and confirm the linked card status."],
    },
  ],
};
