import type { ToolConfig } from "../types";
import { choice, yesNo, yesNoUnsure } from "./shared";

export const readinessConfig: ToolConfig = {
  slug: "readiness",
  name: "China Readiness Check",
  shortName: "Readiness",
  description: "Find the preparation gaps most likely to disrupt your trip.",
  duration: "4 minutes",
  lastReviewedAt: "2026-07-14",
  coveragePoints: [
    "Alipay or WeChat Pay setup, identity checks and a real payment test",
    "Arrival internet and a backup way to get online",
    "Hotel details in Chinese and late-arrival confirmation",
    "Train ticket status and holiday date pressure",
  ],
  sampleFinding: {
    severity: "critical",
    title: "You may arrive without internet access.",
    explanation: "Payment, transport and hotel communication may depend on immediate connectivity.",
  },
  questions: [
    choice("mobilePayment", "Have you set up at least one mobile payment app?", yesNoUnsure, undefined, "Payments"),
    choice("identityVerified", "Is identity verification complete?", yesNoUnsure, undefined, "Payments"),
    choice("paymentTested", "Have you completed a real payment test?", yesNoUnsure, undefined, "Payments"),
    choice("backupCard", "Do you have a second card from another issuer?", yesNo, undefined, "Payments"),
    choice("cashBackup", "Will you carry a small amount of RMB cash?", yesNo, undefined, "Payments"),
    choice("arrivalInternet", "Will you have internet access when you arrive?", yesNoUnsure, undefined, "Internet"),
    choice("backupInternet", "Do you have a backup way to get online?", yesNoUnsure, undefined, "Internet"),
    choice("bankVerificationAccess", "Can you approve bank verification requests?", yesNoUnsure, undefined, "Payments"),
    choice("hotelChineseDetails", "Have you saved the hotel name and address in Chinese?", yesNoUnsure, undefined, "Hotel arrival"),
    choice("lateHotelArrival", "Do you expect to reach the hotel after 11 pm?", yesNo, undefined, "Hotel arrival"),
    { ...choice("lateArrivalConfirmed", "Has the hotel confirmed your late arrival in writing?", yesNoUnsure, undefined, "Hotel arrival"), visibleWhen: { field: "lateHotelArrival", equals: true } },
    choice("trainTravel", "Will you take a train during this trip?", yesNo, undefined, "Transport"),
    { ...choice("trainTicketIssued", "Has your train ticket been formally issued?", yesNoUnsure, undefined, "Transport"), visibleWhen: { field: "trainTravel", equals: true } },
    { ...choice("trainPassportChecked", "Have you checked the passport details on the train booking?", yesNoUnsure, undefined, "Transport"), visibleWhen: { field: "trainTravel", equals: true } },
    choice("holidayDatesChecked", "Have you checked your dates against major Chinese holidays?", yesNoUnsure, undefined, "Travel dates"),
  ],
  rules: [
    {
      code: "READY_PAYMENT_UNVERIFIED", severity: "critical", priority: 1, group: "payment-unverified",
      all: [{ field: "mobilePayment", operator: "eq", value: false }, { field: "cashBackup", operator: "eq", value: false }],
      title: "You do not have a usable arrival payment plan.",
      explanation: "No mobile payment and no cash backup can block transport and basic purchases.",
      actions: ["Set up a mobile payment app.", "Carry emergency RMB cash."],
      relatedCheck: "payment", relatedGuides: ["test-mobile-payment-before-china"],
    },
    {
      code: "READY_NO_MOBILE_PAYMENT", severity: "high", priority: 2, group: "no-mobile-payment",
      all: [{ field: "mobilePayment", operator: "eq", value: false }],
      title: "You have no mobile payment app ready.",
      explanation: "Many everyday purchases in China still expect Alipay or WeChat Pay.",
      actions: ["Set up Alipay or WeChat Pay before departure."],
      relatedCheck: "payment", relatedGuides: ["test-mobile-payment-before-china"],
    },
    {
      code: "READY_IDENTITY", severity: "high", priority: 3, group: "payment-identity",
      all: [{ field: "mobilePayment", operator: "eq", value: true }, { field: "identityVerified", operator: "eq", value: false }],
      title: "Mobile payment identity verification is incomplete.",
      explanation: "An unfinished identity check can block cards, transfers or in-store payments.",
      actions: ["Finish identity verification in the payment app before you travel."],
      relatedCheck: "payment",
    },
    {
      code: "READY_PAYMENT_UNTESTED", severity: "high", priority: 4, group: "payment-untested",
      any: [{ field: "paymentTested", operator: "eq", value: false }, { field: "paymentTested", operator: "eq", value: "unsure" }],
      title: "Your payment setup has not been tested with a real purchase.",
      explanation: "A linked card can still fail when the first real transaction is attempted.",
      actions: ["Complete a small real payment test before departure."],
      relatedCheck: "payment", relatedGuides: ["test-mobile-payment-before-china"],
    },
    {
      code: "READY_PAYMENT_SINGLE", severity: "high", priority: 10, group: "payment-single-point",
      all: [{ field: "backupCard", operator: "eq", value: false }, { field: "cashBackup", operator: "eq", value: false }],
      title: "Your payment plan has no practical backup.",
      explanation: "One account or card problem may remove your only payment path.",
      actions: ["Add a second card or carry emergency cash."], relatedCheck: "payment",
      relatedGuides: ["one-payment-method-is-not-enough"],
    },
    {
      code: "READY_NO_CASH", severity: "information", priority: 40, group: "no-cash-backup",
      all: [{ field: "cashBackup", operator: "eq", value: false }],
      title: "You have no emergency cash backup.",
      explanation: "A modest RMB reserve helps when digital payment is interrupted.",
      actions: ["Carry a small amount of RMB cash."],
      relatedCheck: "payment",
    },
    {
      code: "READY_NO_INTERNET", severity: "critical", priority: 5, group: "no-arrival-internet",
      all: [{ field: "arrivalInternet", operator: "eq", value: false }],
      title: "You may arrive without internet access.",
      explanation: "Payment, transport and hotel communication may depend on immediate connectivity.",
      actions: ["Activate a working data plan before arrival.", "Save essential details offline."],
      relatedGuides: ["arrive-with-working-internet"],
    },
    {
      code: "READY_INTERNET_UNSURE", severity: "high", priority: 6, group: "internet-unsure",
      all: [{ field: "arrivalInternet", operator: "eq", value: "unsure" }],
      title: "Arrival internet access is uncertain.",
      explanation: "If data is not ready on landing, maps and payment apps may fail immediately.",
      actions: ["Confirm a working eSIM or SIM plan before departure."],
      relatedGuides: ["arrive-with-working-internet"],
    },
    {
      code: "READY_NO_BACKUP_INTERNET", severity: "high", priority: 7, group: "no-backup-internet",
      all: [{ field: "backupInternet", operator: "eq", value: false }],
      title: "You have no backup way to get online.",
      explanation: "A single failed eSIM or hotspot can remove payment and navigation at once.",
      actions: ["Prepare a second connectivity option before travel."],
      relatedGuides: ["arrive-with-working-internet"],
    },
    {
      code: "READY_NO_VERIFY", severity: "high", priority: 11, group: "verification-unavailable",
      all: [{ field: "bankVerificationAccess", operator: "eq", value: false }],
      title: "Bank verification may be unavailable.",
      explanation: "Your issuer may require a message or app approval during payment.",
      actions: ["Confirm access to bank messages or app approvals."], relatedCheck: "payment",
      relatedGuides: ["esim-bank-verification-messages"],
    },
    {
      code: "READY_HOTEL_DETAILS", severity: "critical", priority: 8, group: "hotel-location-unusable",
      all: [{ field: "hotelChineseDetails", operator: "eq", value: false }],
      title: "Your hotel details may not be usable on arrival.",
      explanation: "Drivers and local maps may not recognize an English hotel name.",
      actions: ["Save the hotel name and full address in Chinese.", "Save the hotel phone number."],
      relatedCheck: "hotel-arrival", relatedGuides: ["save-hotel-name-address-in-chinese"],
    },
    {
      code: "READY_HOTEL_DETAILS_UNSURE", severity: "high", priority: 9, group: "hotel-details-unsure",
      all: [{ field: "hotelChineseDetails", operator: "eq", value: "unsure" }],
      title: "Hotel Chinese details still need confirmation.",
      explanation: "An incomplete Chinese address can slow taxis and local support.",
      actions: ["Ask the hotel for the Chinese name and full address before departure."],
      relatedCheck: "hotel-arrival", relatedGuides: ["save-hotel-name-address-in-chinese"],
    },
    {
      code: "READY_LATE_HOTEL", severity: "critical", priority: 12, group: "late-arrival-unconfirmed",
      all: [{ field: "lateHotelArrival", operator: "eq", value: true }, { field: "lateArrivalConfirmed", operator: "eq", value: false }],
      title: "Your late hotel arrival is not confirmed.",
      explanation: "The hotel may release the room or close its front desk before you arrive.",
      actions: ["Ask the hotel for written late-arrival confirmation."], relatedCheck: "hotel-arrival",
      relatedGuides: ["confirm-late-hotel-check-in-china"],
    },
    {
      code: "READY_LATE_HOTEL_UNSURE", severity: "high", priority: 13, group: "late-arrival-unsure",
      all: [{ field: "lateHotelArrival", operator: "eq", value: true }, { field: "lateArrivalConfirmed", operator: "eq", value: "unsure" }],
      title: "Late arrival confirmation is still unclear.",
      explanation: "Uncertain late check-in terms leave the room hold at risk.",
      actions: ["Get written confirmation from the hotel before you fly."],
      relatedCheck: "hotel-arrival", relatedGuides: ["confirm-late-hotel-check-in-china"],
    },
    {
      code: "READY_TRAIN_UNISSUED", severity: "high", priority: 14, group: "train-ticket-unissued",
      all: [{ field: "trainTravel", operator: "eq", value: true }, { field: "trainTicketIssued", operator: "eq", value: false }],
      title: "Your train booking may not be a confirmed ticket.",
      explanation: "A request, waitlist or pending order is not the same as an issued ticket.",
      actions: ["Confirm that the train ticket is formally issued."],
    },
    {
      code: "READY_TRAIN_UNSURE", severity: "high", priority: 15, group: "train-ticket-unsure",
      all: [{ field: "trainTravel", operator: "eq", value: true }, { field: "trainTicketIssued", operator: "eq", value: "unsure" }],
      title: "Train ticket status still needs confirmation.",
      explanation: "An unclear booking status can leave you without a seat on busy days.",
      actions: ["Open the booking and confirm it is issued, not pending."],
    },
    {
      code: "READY_TRAIN_PASSPORT", severity: "high", priority: 16, group: "train-passport-unchecked",
      all: [{ field: "trainTravel", operator: "eq", value: true }, { field: "trainPassportChecked", operator: "eq", value: false }],
      title: "Train booking passport details are unchecked.",
      explanation: "A mismatch can prevent ticket verification at the station.",
      actions: ["Compare the booking name and passport number with the physical passport."],
    },
    {
      code: "READY_TRAIN_PASSPORT_UNSURE", severity: "information", priority: 41, group: "train-passport-unsure",
      all: [{ field: "trainTravel", operator: "eq", value: true }, { field: "trainPassportChecked", operator: "eq", value: "unsure" }],
      title: "Train passport details still need a final check.",
      explanation: "A quick passport comparison reduces station delays.",
      actions: ["Compare the booking details with your passport before travel day."],
    },
    {
      code: "READY_HOLIDAY_UNCHECKED", severity: "high", priority: 17, group: "holiday-unchecked",
      all: [{ field: "holidayDatesChecked", operator: "eq", value: false }],
      title: "Your travel dates have not been checked for holiday risk.",
      explanation: "Major holidays can affect transport, accommodation and attraction availability.",
      actions: ["Run the Travel Date Check before finalizing bookings."], relatedCheck: "dates",
      relatedGuides: ["china-holidays-tickets-hotels"],
    },
    {
      code: "READY_HOLIDAY_UNSURE", severity: "information", priority: 42, group: "holiday-unsure",
      all: [{ field: "holidayDatesChecked", operator: "eq", value: "unsure" }],
      title: "Holiday date risk still needs review.",
      explanation: "Busy public holidays can change booking pressure quickly.",
      actions: ["Run the Travel Date Check against your itinerary."],
      relatedCheck: "dates", relatedGuides: ["china-holidays-tickets-hotels"],
    },
  ],
};
