import type { ToolConfig } from "../types";
import { choice, yesNo, yesNoUnsure } from "./shared";

export const readinessConfig: ToolConfig = {
  slug: "readiness",
  name: "China Readiness Check",
  shortName: "Readiness",
  description: "Find the preparation gaps most likely to disrupt your trip.",
  duration: "4 minutes",
  lastReviewedAt: "2026-07-14",
  questions: [
    choice("mobilePayment", "Have you set up at least one mobile payment app?"),
    choice("identityVerified", "Is identity verification complete?"),
    choice("paymentTested", "Have you completed a real payment test?"),
    choice("backupCard", "Do you have a second card from another issuer?", yesNo),
    choice("cashBackup", "Will you carry a small amount of RMB cash?", yesNo),
    choice("arrivalInternet", "Will you have internet access when you arrive?"),
    choice("backupInternet", "Do you have a backup way to get online?"),
    choice("bankVerificationAccess", "Can you approve bank verification requests?"),
    choice("hotelChineseDetails", "Have you saved the hotel name and address in Chinese?"),
    choice("lateHotelArrival", "Do you expect to reach the hotel after 11 pm?", yesNo),
    { ...choice("lateArrivalConfirmed", "Has the hotel confirmed your late arrival in writing?"), visibleWhen: { field: "lateHotelArrival", equals: true } },
    choice("trainTravel", "Will you take a train during this trip?", yesNo),
    { ...choice("trainTicketIssued", "Has your train ticket been formally issued?", yesNoUnsure), visibleWhen: { field: "trainTravel", equals: true } },
    { ...choice("trainPassportChecked", "Have you checked the passport details on the train booking?", yesNoUnsure), visibleWhen: { field: "trainTravel", equals: true } },
    choice("holidayDatesChecked", "Have you checked your dates against major Chinese holidays?"),
  ],
  rules: [
    {
      code: "READY_PAYMENT_UNVERIFIED", severity: "critical", priority: 1, group: "payment-unverified",
      all: [{ field: "mobilePayment", operator: "eq", value: false }, { field: "cashBackup", operator: "eq", value: false }],
      title: "You do not have a usable arrival payment plan.",
      explanation: "No mobile payment and no cash backup can block transport and basic purchases.",
      actions: ["Set up a mobile payment app.", "Carry emergency RMB cash."],
      relatedCheck: "payment", relatedGuides: ["test-mobile-payment-before-china"],
    },
    {
      code: "READY_PAYMENT_SINGLE", severity: "high", priority: 10, group: "payment-single-point",
      all: [{ field: "backupCard", operator: "eq", value: false }, { field: "cashBackup", operator: "eq", value: false }],
      title: "Your payment plan has no practical backup.",
      explanation: "One account or card problem may remove your only payment path.",
      actions: ["Add a second card or carry emergency cash."], relatedCheck: "payment",
      relatedGuides: ["one-payment-method-is-not-enough"],
    },
    {
      code: "READY_NO_INTERNET", severity: "critical", priority: 2, group: "no-arrival-internet",
      all: [{ field: "arrivalInternet", operator: "eq", value: false }],
      title: "You may arrive without internet access.",
      explanation: "Payment, transport and hotel communication may depend on immediate connectivity.",
      actions: ["Activate a working data plan before arrival.", "Save essential details offline."],
    },
    {
      code: "READY_NO_VERIFY", severity: "high", priority: 11, group: "verification-unavailable",
      all: [{ field: "bankVerificationAccess", operator: "eq", value: false }],
      title: "Bank verification may be unavailable.",
      explanation: "Your issuer may require a message or app approval during payment.",
      actions: ["Confirm access to bank messages or app approvals."], relatedCheck: "payment",
    },
    {
      code: "READY_HOTEL_DETAILS", severity: "critical", priority: 3, group: "hotel-location-unusable",
      all: [{ field: "hotelChineseDetails", operator: "eq", value: false }],
      title: "Your hotel details may not be usable on arrival.",
      explanation: "Drivers and local maps may not recognize an English hotel name.",
      actions: ["Save the hotel name and full address in Chinese.", "Save the hotel phone number."],
      relatedCheck: "hotel-arrival", relatedGuides: ["save-hotel-name-address-in-chinese"],
    },
    {
      code: "READY_LATE_HOTEL", severity: "critical", priority: 4, group: "late-arrival-unconfirmed",
      all: [{ field: "lateHotelArrival", operator: "eq", value: true }, { field: "lateArrivalConfirmed", operator: "eq", value: false }],
      title: "Your late hotel arrival is not confirmed.",
      explanation: "The hotel may release the room or close its front desk before you arrive.",
      actions: ["Ask the hotel for written late-arrival confirmation."], relatedCheck: "hotel-arrival",
      relatedGuides: ["confirm-late-hotel-check-in-china"],
    },
    {
      code: "READY_TRAIN_UNISSUED", severity: "high", priority: 12, group: "train-ticket-unissued",
      all: [{ field: "trainTravel", operator: "eq", value: true }, { field: "trainTicketIssued", operator: "eq", value: false }],
      title: "Your train booking may not be a confirmed ticket.",
      explanation: "A request, waitlist or pending order is not the same as an issued ticket.",
      actions: ["Confirm that the train ticket is formally issued."],
    },
    {
      code: "READY_TRAIN_PASSPORT", severity: "high", priority: 13, group: "train-passport-unchecked",
      all: [{ field: "trainTravel", operator: "eq", value: true }, { field: "trainPassportChecked", operator: "eq", value: false }],
      title: "Train booking passport details are unchecked.",
      explanation: "A mismatch can prevent ticket verification at the station.",
      actions: ["Compare the booking name and passport number with the physical passport."],
    },
    {
      code: "READY_HOLIDAY_UNCHECKED", severity: "high", priority: 14, group: "holiday-unchecked",
      all: [{ field: "holidayDatesChecked", operator: "eq", value: false }],
      title: "Your travel dates have not been checked for holiday risk.",
      explanation: "Major holidays can affect transport, accommodation and attraction availability.",
      actions: ["Run the Travel Date Check before finalizing bookings."], relatedCheck: "dates",
      relatedGuides: ["china-holidays-tickets-hotels"],
    },
  ],
};
