import type { ToolConfig } from "../types";
import { choice, yesNo, yesNoUnsure } from "./shared";

export const trainBookingConfig: ToolConfig = {
  slug: "train-booking",
  name: "China Train Booking Diagnostic",
  shortName: "Train diagnostic",
  description: "Diagnose 12306 passport verification, ticket status and itinerary dependency risks before train day.",
  duration: "5 minutes",
  lastReviewedAt: "2026-08-10",
  coveragePoints: [
    "12306 foreign-passport verification failures",
    "Trip.com reservation, pending, waitlist and issued statuses",
    "Ticket confirmation and itinerary dependency risk",
    "Original passport, connection and backup train preparation",
  ],
  sampleFinding: {
    severity: "critical",
    title: "Your reservation is not an issued train ticket.",
    explanation: "A request, pending order or waitlist does not guarantee a seat, especially when the itinerary depends on this train.",
  },
  faqs: [
    { question: "Why is my 12306 passport verification not working?", answer: "Common failure points include the passenger name format, passport image upload, review status and the interface used. This diagnostic narrows the likely cause and tells you whether to retry, wait or prepare another booking channel." },
    { question: "Is a Trip.com reservation a confirmed China train ticket?", answer: "Not necessarily. Treat the booking as confirmed only when the provider shows that the ticket is issued or ticketed for the correct passenger." },
    { question: "Does a waitlist percentage mean I have a ticket?", answer: "No. A waitlist or success estimate is not an issued ticket. Protect any linked hotel, flight or attraction with another train or a flexible itinerary." },
  ],
  sources: [
    { label: "12306 English FAQ", url: "https://www.12306.cn/en/faq.html" },
    { label: "12306 English site", url: "https://www.12306.cn/en/index.html" },
    { label: "Trip.com 12306 guide", url: "https://us.trip.com/guide/train/12306.html" },
  ],
  questions: [
    { id: "ticketChannel", prompt: "Where are you booking the train?", type: "single", required: true, section: "Booking channel", options: [
      { label: "Railway 12306", value: "12306" },
      { label: "Trip.com", value: "trip" },
      { label: "Station counter or another agent", value: "station" },
      { label: "I have not chosen", value: "none" },
    ] },
    { id: "platformMode", prompt: "Which 12306 interface are you using?", type: "single", required: true, section: "12306 verification", visibleWhen: { field: "ticketChannel", equals: "12306" }, options: [
      { label: "English app or website", value: "english" },
      { label: "Chinese app or website", value: "chinese" },
      { label: "I am not sure", value: "unsure" },
    ] },
    { id: "verificationStatus", prompt: "What is the passport verification status?", type: "single", required: true, section: "Passenger verification", options: [
      { label: "Verified or accepted", value: "verified" },
      { label: "Still under review", value: "pending" },
      { label: "Failed or rejected", value: "failed" },
      { label: "Not submitted", value: "not-submitted" },
      { label: "I cannot tell", value: "unsure" },
    ] },
    { id: "verificationError", prompt: "What happens when verification fails?", type: "single", required: true, section: "Failure diagnosis", visibleWhen: { field: "verificationStatus", equals: "failed" }, options: [
      { label: "System busy or generic error", value: "system-busy" },
      { label: "Passport photo will not upload", value: "photo-upload" },
      { label: "Name or passenger details rejected", value: "name-format" },
      { label: "Document type is not accepted", value: "document-type" },
      { label: "Another or unclear error", value: "other" },
    ] },
    { id: "photoMethod", prompt: "How did you prepare the passport image?", type: "single", required: true, section: "12306 verification", visibleWhen: { field: "ticketChannel", equals: "12306" }, options: [
      { label: "Clear camera photo of the original passport", value: "camera" },
      { label: "Scan", value: "scan" },
      { label: "Screenshot or edited image", value: "screenshot" },
      { label: "No image submitted", value: "none" },
    ] },
    { id: "phoneType", prompt: "What phone number is attached to the account?", type: "single", required: true, section: "Account recovery", visibleWhen: { field: "ticketChannel", equals: "12306" }, options: [
      { label: "Mainland China number", value: "china" },
      { label: "International number", value: "international" },
      { label: "No number or unsure", value: "unsure" },
    ] },
    choice("phoneAccess", "Can you reliably access the booking email or phone?", yesNoUnsure, undefined, "Account recovery"),
    choice("nameMatches", "Does the passenger name exactly match the passport record?", yesNoUnsure, "Compare spelling, order and document number with the original passport.", "Passenger details"),
    { id: "ticketStatus", prompt: "What status does the booking show now?", type: "single", required: true, section: "Ticket confirmation", options: [
      { label: "Issued or ticketed", value: "issued" },
      { label: "Reserved or requested", value: "reserved" },
      { label: "Pending or processing", value: "pending" },
      { label: "Waitlisted or shows a success percentage", value: "waitlisted" },
      { label: "Awaiting payment", value: "awaiting-payment" },
      { label: "Sold out", value: "sold-out" },
      { label: "Not booked or unsure", value: "none" },
    ] },
    { id: "departureWindow", prompt: "How soon is the train?", type: "single", required: true, section: "Itinerary risk", options: [
      { label: "Within 2 days", value: "0-2" },
      { label: "3–7 days", value: "3-7" },
      { label: "8–15 days", value: "8-15" },
      { label: "More than 15 days", value: "16-plus" },
    ] },
    choice("backupTrain", "Do you have a workable backup train or route?", yesNoUnsure, undefined, "Itinerary risk"),
    choice("criticalDependency", "Does a flight, fixed hotel, attraction or last connection depend on this train?", yesNo, undefined, "Itinerary risk"),
    choice("hasTransfer", "Will you change trains during the journey?", yesNo, undefined, "Connections"),
    { ...choice("transferBuffer", "Is the connection buffer at least 30 minutes?", [{ label: "Yes", value: "30-plus" }, { label: "No", value: "under-30" }, { label: "Unsure", value: "unsure" }], undefined, "Connections"), visibleWhen: { field: "hasTransfer", equals: true } },
    choice("originalPassportCarry", "Will you carry the original passport used for booking?", yesNo, undefined, "Train day"),
  ],
  rules: [
    { code: "TRAIN_NO_CHANNEL", severity: "critical", priority: 1, group: "train-channel", all: [{ field: "ticketChannel", operator: "eq", value: "none" }], title: "You do not have a usable booking channel yet.", explanation: "Passenger verification and ticket confirmation cannot begin until a channel is chosen.", actions: ["Choose 12306, Trip.com or a staffed station counter."], relatedGuides: ["train-booking-for-foreign-visitors"] },
    { code: "TRAIN_NAME_MISMATCH", severity: "critical", priority: 2, group: "train-name", all: [{ field: "nameMatches", operator: "not-yes" }], title: "The passenger record may not match the passport.", explanation: "A name or document mismatch can block verification and station access.", actions: ["Correct the passenger spelling, order and document number before relying on the booking."], relatedGuides: ["train-booking-for-foreign-visitors"] },
    { code: "TRAIN_VERIFY_NAME", severity: "high", priority: 3, group: "train-verification-name", all: [{ field: "verificationStatus", operator: "eq", value: "failed" }, { field: "verificationError", operator: "eq", value: "name-format" }], title: "The passport name format is the likely blocker.", explanation: "12306 is rejecting the passenger details rather than confirming the identity record.", actions: ["Re-enter the name exactly as shown in the passport machine-readable and biographical fields.", "Remove unsupported punctuation and compare document number and nationality."], backup: "Keep Trip.com or a staffed station counter available if the record cannot be corrected before sales open.", relatedGuides: ["train-booking-for-foreign-visitors"] },
    { code: "TRAIN_VERIFY_PHOTO", severity: "high", priority: 4, group: "train-verification-photo", all: [{ field: "verificationStatus", operator: "eq", value: "failed" }], any: [{ field: "verificationError", operator: "eq", value: "photo-upload" }, { field: "photoMethod", operator: "eq", value: "screenshot" }, { field: "photoMethod", operator: "eq", value: "none" }], title: "The passport image is the likely verification blocker.", explanation: "Screenshots, edited images, glare or unreadable passport details can prevent upload or review.", actions: ["Retake a clear image of the original passport in even light.", "Keep all document edges and details visible and retry from a stable connection."], backup: "Use another booking channel if image verification cannot be completed before ticket release.", relatedGuides: ["train-booking-for-foreign-visitors"] },
    { code: "TRAIN_VERIFY_BUSY", severity: "information", priority: 15, group: "train-verification-busy", all: [{ field: "verificationStatus", operator: "eq", value: "failed" }, { field: "verificationError", operator: "eq", value: "system-busy" }], title: "The failure looks temporary rather than document-specific.", explanation: "A generic system-busy response does not prove that the passport details are wrong.", actions: ["Save the entered details, wait and retry once from a stable connection.", "Avoid repeated rapid submissions."], backup: "Prepare Trip.com or station-counter booking if the error persists near ticket release." },
    { code: "TRAIN_VERIFY_OTHER", severity: "high", priority: 5, group: "train-verification-other", all: [{ field: "verificationStatus", operator: "eq", value: "failed" }], any: [{ field: "verificationError", operator: "eq", value: "document-type" }, { field: "verificationError", operator: "eq", value: "other" }], title: "The passport record was rejected without a recoverable match.", explanation: "The visible error does not point to a simple name or image correction.", actions: ["Compare the accepted document types and passenger details with the current 12306 instructions.", "Use official support rather than repeatedly resubmitting unchanged data."], backup: "Prepare Trip.com or a staffed station counter as an independent booking path.", relatedGuides: ["train-booking-for-foreign-visitors"] },
    { code: "TRAIN_VERIFY_PENDING", severity: "high", priority: 5, group: "train-verification-pending", all: [{ field: "verificationStatus", operator: "eq", value: "pending" }], title: "Passport verification is still under review.", explanation: "You do not yet have a proven 12306 passenger record for ticket purchase.", actions: ["Wait for the stated review period and check the passenger status again.", "Prepare a fallback booking channel before sales open."], backup: "Trip.com or a staffed counter may be sensible if verification remains pending." },
    { code: "TRAIN_VERIFY_NOT_SUBMITTED", severity: "high", priority: 6, group: "train-verification-not-submitted", any: [{ field: "verificationStatus", operator: "eq", value: "not-submitted" }, { field: "verificationStatus", operator: "eq", value: "unsure" }], title: "Passport verification has not been proven complete.", explanation: "An account alone does not create a verified foreign-passport passenger record.", actions: ["Open the passenger record and submit or confirm identity verification."], backup: "Do not wait until ticket release day to discover the account cannot purchase." },
    { code: "TRAIN_STATUS_UNCONFIRMED", severity: "high", priority: 7, group: "train-ticket-not-issued", any: [{ field: "ticketStatus", operator: "eq", value: "reserved" }, { field: "ticketStatus", operator: "eq", value: "pending" }, { field: "ticketStatus", operator: "eq", value: "awaiting-payment" }, { field: "ticketStatus", operator: "eq", value: "none" }], title: "NOT YET TICKETED — this is not a confirmed seat.", explanation: "Reserved, requested, pending and awaiting-payment states are not the same as an issued ticket.", actions: ["Check for an issued or ticketed status for the correct passenger.", "Set a deadline for switching to a backup train."], relatedGuides: ["train-booking-for-foreign-visitors"] },
    { code: "TRAIN_WAITLIST", severity: "critical", priority: 8, group: "train-waitlist-risk", any: [{ field: "ticketStatus", operator: "eq", value: "waitlisted" }, { field: "ticketStatus", operator: "eq", value: "sold-out" }], title: "WAITLIST RISK — you do not currently have a ticket.", explanation: "A success percentage, waitlist position or sold-out result does not guarantee travel.", actions: ["Choose a later or earlier train, another route or a flexible travel date.", "Do not treat the estimated success rate as confirmation."], backup: "Keep at least one independently bookable alternative." },
    { code: "TRAIN_IMMINENT_UNISSUED", severity: "critical", priority: 8, group: "train-imminent-unissued", all: [{ field: "departureWindow", operator: "eq", value: "0-2" }, { field: "ticketStatus", operator: "neq", value: "issued" }], title: "Departure is within two days and the ticket is still unissued.", explanation: "The remaining recovery window is short, so waiting without another bookable route creates a critical travel risk.", actions: ["Book or hold a workable alternative now.", "Recheck the original order only after the backup path is protected."], backup: "Use another train, station or route that can be confirmed independently." },
    { code: "TRAIN_CRITICAL_DEPENDENCY", severity: "critical", priority: 9, group: "train-critical-dependency", all: [{ field: "criticalDependency", operator: "eq", value: true }, { field: "backupTrain", operator: "not-yes" }], any: [{ field: "ticketStatus", operator: "neq", value: "issued" }], title: "CRITICAL ITINERARY DEPENDENCY — the trip relies on an unissued ticket.", explanation: "A flight, fixed hotel, attraction or last connection could fail with this train booking.", actions: ["Add a confirmed backup train or make the linked booking flexible.", "Avoid a same-day dependency until the ticket is issued."], backup: "Save an alternative route that still protects the fixed booking." },
    { code: "TRAIN_NO_BACKUP", severity: "high", priority: 10, group: "train-no-backup", all: [{ field: "backupTrain", operator: "not-yes" }], any: [{ field: "ticketStatus", operator: "neq", value: "issued" }], title: "The unconfirmed train has no workable backup.", explanation: "A pending or waitlisted booking can fail without leaving enough time to recover.", actions: ["Identify another train, route or travel date now."], backup: "Keep the backup independent of the same waitlist." },
    { code: "TRAIN_PHONE", severity: "high", priority: 11, group: "train-contact", all: [{ field: "phoneAccess", operator: "not-yes" }], title: "Booking recovery contact access is uncertain.", explanation: "Notices and account recovery may depend on the attached email or phone.", actions: ["Confirm access to the booking contact method before departure."] },
    { code: "TRAIN_TRANSFER", severity: "high", priority: 12, group: "train-transfer", any: [{ field: "transferBuffer", operator: "eq", value: "under-30" }, { field: "transferBuffer", operator: "eq", value: "unsure" }], title: "The connection may be too tight for an unfamiliar station.", explanation: "Platform changes, queues and long corridors can consume a short transfer.", actions: ["Choose at least a 30-minute connection or a direct train."] },
    { code: "TRAIN_PASSPORT", severity: "high", priority: 13, group: "train-passport", all: [{ field: "originalPassportCarry", operator: "eq", value: false }], title: "The original booking passport will not be available.", explanation: "The original passport may be needed for station identity checks and manual assistance.", actions: ["Carry the original passport used in the passenger record."], relatedGuides: ["train-booking-for-foreign-visitors"] },
  ],
};
